var arrayRerum = {
	1 :"Aeneadum genetrix, hominum divomque voluptas,",
	2 :"alma Venus, caeli subter labentia signa",
	3 :"quae mare navigerum, quae terras frugiferentis",
	4 :"concelebras, per te quoniam genus omne animantum",
	5 :"concipitur visitque exortum lumina solis:",
	6 :"te, dea, te fugiunt venti, te nubila caeli",
	7 :"adventumque tuum, tibi suavis daedala tellus",
	8 :"summittit flores, tibi rident aequora ponti",
	9 :"placatumque nitet diffuso lumine caelum.",
	10 :"nam simul ac species patefactast verna diei",
	11 :"et reserata viget genitabilis aura favoni,",
	12 :"aeriae primum volucris te, diva, tuumque",
	13 :"significant initum perculsae corda tua vi.",
	14 :"inde ferae pecudes persultant pabula laeta",
	15 :"et rapidos tranant amnis: ita capta lepore",
	16 :"te sequitur cupide quo quamque inducere pergis.",
	17 :"denique per maria ac montis fluviosque rapacis",
	18 :"frondiferasque domos avium camposque virentis",
	19 :"omnibus incutiens blandum per pectora amorem",
	20 :"efficis ut cupide generatim saecla propagent.",
	21 :"quae quoniam rerum naturam sola gubernas",
	22 :"nec sine te quicquam dias in luminis oras",
	23 :"exoritur neque fit laetum neque amabile quicquam,",
	24 :"te sociam studeo scribendis versibus esse,",
	25 :"quos ego de rerum natura pangere conor",
	26 :"Memmiadae nostro, quem tu, dea, tempore in omni",
	27 :"omnibus ornatum voluisti excellere rebus.",
	28 :"quo magis aeternum da dictis, diva, leporem.",
	29 :"effice ut interea fera moenera militiai",
	30 :"per maria ac terras omnis sopita quiescant;",
	31 :"nam tu sola potes tranquilla pace iuvare",
	32 :"mortalis, quoniam belli fera moenera Mavors",
	33 :"armipotens regit, in gremium qui saepe tuum se",
	34 :"reiicit aeterno devictus vulnere amoris,",
	35 :"atque ita suspiciens tereti cervice reposta",
	36 :"pascit amore avidos inhians in te, dea, visus",
	37 :"eque tuo pendet resupini spiritus ore.",
	38 :"hunc tu, diva, tuo recubantem corpore sancto",
	39 :"circum fusa super, suavis ex ore loquellas",
	40 :"funde petens placidam Romanis, incluta, pacem;",
	41 :"nam neque nos agere hoc patriai tempore iniquo",
	42 :"possumus aequo animo nec Memmi clara propago",
	43 :"talibus in rebus communi desse saluti.",
	44 :"omnis enim per se divum natura necessest",
	45 :"immortali aevo summa cum pace fruatur",
	46 :"semota ab nostris rebus seiunctaque longe;",
	47 :"nam privata dolore omni, privata periclis,",
	48 :"ipsa suis pollens opibus, nihil indiga nostri,",
	49 :"nec bene promeritis capitur nec tangitur ira.",
	50 :"Quod super est, vacuas auris animumque sagacem",
	51 :"semotum a curis adhibe veram ad rationem,",
	52 :"ne mea dona tibi studio disposta fideli,",
	53 :"intellecta prius quam sint, contempta relinquas.",
	54 :"nam tibi de summa caeli ratione deumque",
	55 :"disserere incipiam et rerum primordia pandam,",
	56 :"unde omnis natura creet res, auctet alatque,",
	57 :"quove eadem rursum natura perempta resolvat,",
	58 :"quae nos materiem et genitalia corpora rebus",
	59 :"reddunda in ratione vocare et semina rerum",
	60 :"appellare suemus et haec eadem usurpare",
	61 :"corpora prima, quod ex illis sunt omnia primis.",
	62 :"Humana ante oculos foede cum vita iaceret",
	63 :"in terris oppressa gravi sub religione,",
	64 :"quae caput a caeli regionibus ostendebat",
	65 :"horribili super aspectu mortalibus instans,",
	66 :"primum Graius homo mortalis tollere contra",
	67 :"est oculos ausus primusque obsistere contra;",
	68 :"quem neque fama deum nec fulmina nec minitanti",
	69 :"murmure compressit caelum, sed eo magis acrem",
	70 :"inritat animi virtutem, effringere ut arta",
	71 :"naturae primus portarum claustra cupiret.",
	72 :"ergo vivida vis animi pervicit et extra",
	73 :"processit longe flammantia moenia mundi",
	74 :"atque omne immensum peragravit mente animoque,",
	75 :"unde refert nobis victor quid possit oriri,",
	76 :"quid nequeat, finita potestas denique cuique",
	77 :"quanam sit ratione atque alte terminus haerens.",
	78 :"quare religio pedibus subiecta vicissim",
	79 :"opteritur, nos exaequat victoria caelo.",
	80 :"Illud in his rebus vereor, ne forte rearis",
	81 :"impia te rationis inire elementa viamque",
	82 :"indugredi sceleris. quod contra saepius illa",
	83 :"religio peperit scelerosa atque impia facta.",
	84 :"Aulide quo pacto Triviai virginis aram",
	85 :"Iphianassai turparunt sanguine foede",
	86 :"ductores Danaum delecti, prima virorum.",
	87 :"cui simul infula virgineos circumdata comptus",
	88 :"ex utraque pari malarum parte profusast,",
	89 :"et maestum simul ante aras adstare parentem",
	90 :"sensit et hunc propter ferrum celare ministros",
	91 :"aspectuque suo lacrimas effundere civis,",
	92 :"muta metu terram genibus summissa petebat.",
	93 :"nec miserae prodesse in tali tempore quibat,",
	94 :"quod patrio princeps donarat nomine regem;",
	95 :"nam sublata virum manibus tremibundaque ad aras",
	96 :"deductast, non ut sollemni more sacrorum",
	97 :"perfecto posset claro comitari Hymenaeo,",
	98 :"sed casta inceste nubendi tempore in ipso",
	99 :"hostia concideret mactatu maesta parentis,",
	100 :"exitus ut classi felix faustusque daretur.",
	101 :"tantum religio potuit suadere malorum.",
	102 :"Tutemet a nobis iam quovis tempore vatum",
	103 :"terriloquis victus dictis desciscere quaeres.",
	104 :"quippe etenim quam multa tibi iam fingere possunt",
	105 :"somnia, quae vitae rationes vertere possint",
	106 :"fortunasque tuas omnis turbare timore!",
	107 :"et merito; nam si certam finem esse viderent",
	108 :"aerumnarum homines, aliqua ratione valerent",
	109 :"religionibus atque minis obsistere vatum.",
	110 :"nunc ratio nulla est restandi, nulla facultas,",
	111 :"aeternas quoniam poenas in morte timendum.",
	112 :"ignoratur enim quae sit natura animai,",
	113 :"nata sit an contra nascentibus insinuetur",
	114 :"et simul intereat nobiscum morte dirempta",
	115 :"an tenebras Orci visat vastasque lacunas",
	116 :"an pecudes alias divinitus insinuet se,",
	117 :"Ennius ut noster cecinit, qui primus amoeno",
	118 :"detulit ex Helicone perenni fronde coronam,",
	119 :"per gentis Italas hominum quae clara clueret;",
	120 :"etsi praeterea tamen esse Acherusia templa",
	121 :"Ennius aeternis exponit versibus edens,",
	122 :"quo neque permaneant animae neque corpora nostra,",
	123 :"sed quaedam simulacra modis pallentia miris;",
	124 :"unde sibi exortam semper florentis Homeri",
	125 :"commemorat speciem lacrimas effundere salsas",
	126 :"coepisse et rerum naturam expandere dictis.",
	127 :"qua propter bene cum superis de rebus habenda",
	128 :"nobis est ratio, solis lunaeque meatus",
	129 :"qua fiant ratione, et qua vi quaeque gerantur",
	130 :"in terris, tunc cum primis ratione sagaci",
	131 :"unde anima atque animi constet natura videndum,",
	132 :"et quae res nobis vigilantibus obvia mentes",
	133 :"terrificet morbo adfectis somnoque sepultis,",
	134 :"cernere uti videamur eos audireque coram,",
	135 :"morte obita quorum tellus amplectitur ossa.",
	136 :"Nec me animi fallit Graiorum obscura reperta",
	137 :"difficile inlustrare Latinis versibus esse,",
	138 :"multa novis verbis praesertim cum sit agendum",
	139 :"propter egestatem linguae et rerum novitatem;",
	140 :"sed tua me virtus tamen et sperata voluptas",
	141 :"suavis amicitiae quemvis efferre laborem",
	142 :"suadet et inducit noctes vigilare serenas",
	143 :"quaerentem dictis quibus et quo carmine demum",
	144 :"clara tuae possim praepandere lumina menti,",
	145 :"res quibus occultas penitus convisere possis.",
	146 :"hunc igitur terrorem animi tenebrasque necessest",
	147 :"non radii solis neque lucida tela diei",
	148 :"discutiant, sed naturae species ratioque.",
	149 :"Principium cuius hinc nobis exordia sumet,",
	150 :"nullam rem e nihilo gigni divinitus umquam.",
	151 :"quippe ita formido mortalis continet omnis,",
	152 :"quod multa in terris fieri caeloque tuentur,",
	153 :"quorum operum causas nulla ratione videre",
	154 :"possunt ac fieri divino numine rentur.",
	155 :"quas ob res ubi viderimus nil posse creari",
	156 :"de nihilo, tum quod sequimur iam rectius inde",
	157 :"perspiciemus, et unde queat res quaeque creari",
	158 :"et quo quaeque modo fiant opera sine divom.",
	159 :"Nam si de nihilo fierent, ex omnibus rebus",
	160 :"omne genus nasci posset, nil semine egeret.",
	161 :"e mare primum homines, e terra posset oriri",
	162 :"squamigerum genus et volucres erumpere caelo;",
	163 :"armenta atque aliae pecudes, genus omne ferarum,",
	164 :"incerto partu culta ac deserta tenerent.",
	165 :"nec fructus idem arboribus constare solerent,",
	166 :"sed mutarentur, ferre omnes omnia possent.",
	167 :"quippe ubi non essent genitalia corpora cuique,",
	168 :"qui posset mater rebus consistere certa?",
	169 :"at nunc seminibus quia certis quaeque creantur,",
	170 :"inde enascitur atque oras in luminis exit,",
	171 :"materies ubi inest cuiusque et corpora prima;",
	172 :"atque hac re nequeunt ex omnibus omnia gigni,",
	173 :"quod certis in rebus inest secreta facultas.",
	174 :"Praeterea cur vere rosam, frumenta calore,",
	175 :"vites autumno fundi suadente videmus,",
	176 :"si non, certa suo quia tempore semina rerum",
	177 :"cum confluxerunt, patefit quod cumque creatur,",
	178 :"dum tempestates adsunt et vivida tellus",
	179 :"tuto res teneras effert in luminis oras?",
	180 :"quod si de nihilo fierent, subito exorerentur",
	181 :"incerto spatio atque alienis partibus anni,",
	182 :"quippe ubi nulla forent primordia, quae genitali",
	183 :"concilio possent arceri tempore iniquo.",
	184 :"Nec porro augendis rebus spatio foret usus",
	185 :"seminis ad coitum, si e nilo crescere possent;",
	186 :"nam fierent iuvenes subito ex infantibus parvis",
	187 :"e terraque exorta repente arbusta salirent.",
	188 :"quorum nil fieri manifestum est, omnia quando",
	189 :"paulatim crescunt, ut par est semine certo,",
	190 :"crescentesque genus servant; ut noscere possis",
	191 :"quicque sua de materia grandescere alique.",
	192 :"Huc accedit uti sine certis imbribus anni",
	193 :"laetificos nequeat fetus submittere tellus",
	194 :"nec porro secreta cibo natura animantum",
	195 :"propagare genus possit vitamque tueri;",
	196 :"ut potius multis communia corpora rebus",
	197 :"multa putes esse, ut verbis elementa videmus,",
	198 :"quam sine principiis ullam rem existere posse.",
	199 :"Denique cur homines tantos natura parare",
	200 :"non potuit, pedibus qui pontum per vada possent",
	201 :"transire et magnos manibus divellere montis",
	202 :"multaque vivendo vitalia vincere saecla,",
	203 :"si non, materies quia rebus reddita certast",
	204 :"gignundis, e qua constat quid possit oriri?",
	205 :"nil igitur fieri de nilo posse fatendumst,",
	206 :"semine quando opus est rebus, quo quaeque creatae",
	207 :"aeris in teneras possint proferrier auras.",
	208 :"Postremo quoniam incultis praestare videmus",
	209 :"culta loca et manibus melioris reddere fetus,",
	210 :"esse videlicet in terris primordia rerum",
	211 :"quae nos fecundas vertentes vomere glebas",
	212 :"terraique solum subigentes cimus ad ortus;",
	213 :"quod si nulla forent, nostro sine quaeque labore",
	214 :"sponte sua multo fieri meliora videres.",
	215 :"Huc accedit uti quicque in sua corpora rursum",
	216 :"dissoluat natura neque ad nihilum interemat res.",
	217 :"nam siquid mortale e cunctis partibus esset,",
	218 :"ex oculis res quaeque repente erepta periret;",
	219 :"nulla vi foret usus enim, quae partibus eius",
	220 :"discidium parere et nexus exsolvere posset.",
	221 :"quod nunc, aeterno quia constant semine quaeque,",
	222 :"donec vis obiit, quae res diverberet ictu",
	223 :"aut intus penetret per inania dissoluatque,",
	224 :"nullius exitium patitur natura videri.",
	225 :"Praeterea quae cumque vetustate amovet aetas,",
	226 :"si penitus peremit consumens materiem omnem,",
	227 :"unde animale genus generatim in lumina vitae",
	228 :"redducit Venus, aut redductum daedala tellus",
	229 :"unde alit atque auget generatim pabula praebens?",
	230 :"unde mare ingenuei fontes externaque longe",
	231 :"flumina suppeditant? unde aether sidera pascit?",
	232 :"omnia enim debet, mortali corpore quae sunt,",
	233 :"infinita aetas consumpse ante acta diesque.",
	234 :"quod si in eo spatio atque ante acta aetate fuere",
	235 :"e quibus haec rerum consistit summa refecta,",
	236 :"inmortali sunt natura praedita certe.",
	237 :"haud igitur possunt ad nilum quaeque reverti.",
	238 :"Denique res omnis eadem vis causaque volgo",
	239 :"conficeret, nisi materies aeterna teneret,",
	240 :"inter se nexus minus aut magis indupedita;",
	241 :"tactus enim leti satis esset causa profecto,",
	242 :"quippe ubi nulla forent aeterno corpore, quorum",
	243 :"contextum vis deberet dissolvere quaeque.",
	244 :"at nunc, inter se quia nexus principiorum",
	245 :"dissimiles constant aeternaque materies est,",
	246 :"incolumi remanent res corpore, dum satis acris",
	247 :"vis obeat pro textura cuiusque reperta.",
	248 :"haud igitur redit ad nihilum res ulla, sed omnes",
	249 :"discidio redeunt in corpora materiai.",
	250 :"postremo pereunt imbres, ubi eos pater aether",
	251 :"in gremium matris terrai praecipitavit;",
	252 :"at nitidae surgunt fruges ramique virescunt",
	253 :"arboribus, crescunt ipsae fetuque gravantur.",
	254 :"hinc alitur porro nostrum genus atque ferarum,",
	255 :"hinc laetas urbes pueris florere videmus",
	256 :"frondiferasque novis avibus canere undique silvas,",
	257 :"hinc fessae pecudes pinguis per pabula laeta",
	258 :"corpora deponunt et candens lacteus umor",
	259 :"uberibus manat distentis, hinc nova proles",
	260 :"artubus infirmis teneras lasciva per herbas",
	261 :"ludit lacte mero mentes perculsa novellas.",
	262 :"haud igitur penitus pereunt quaecumque videntur,",
	263 :"quando alit ex alio reficit natura nec ullam",
	264 :"rem gigni patitur nisi morte adiuta aliena.",
	265 :"Nunc age, res quoniam docui non posse creari",
	266 :"de nihilo neque item genitas ad nil revocari,",
	267 :"ne qua forte tamen coeptes diffidere dictis,",
	268 :"quod nequeunt oculis rerum primordia cerni,",
	269 :"accipe praeterea quae corpora tute necessest",
	270 :"confiteare esse in rebus nec posse videri.",
	271 :"Principio venti vis verberat incita corpus",
	272 :"ingentisque ruit navis et nubila differt,",
	273 :"inter dum rapido percurrens turbine campos",
	274 :"arboribus magnis sternit montisque supremos",
	275 :"silvifragis vexat flabris: ita perfurit acri",
	276 :"cum fremitu saevitque minaci murmure pontus.",
	277 :"sunt igitur venti ni mirum corpora caeca,",
	278 :"quae mare, quae terras, quae denique nubila caeli",
	279 :"verrunt ac subito vexantia turbine raptant,",
	280 :"nec ratione fluunt alia stragemque propagant",
	281 :"et cum mollis aquae fertur natura repente",
	282 :"flumine abundanti, quam largis imbribus auget",
	283 :"montibus ex altis magnus decursus aquai",
	284 :"fragmina coniciens silvarum arbustaque tota,",
	285 :"nec validi possunt pontes venientis aquai",
	286 :"vim subitam tolerare: ita magno turbidus imbri",
	287 :"molibus incurrit validis cum viribus amnis,",
	288 :"dat sonitu magno stragem volvitque sub undis",
	289 :"grandia saxa, ruit qua quidquid fluctibus obstat.",
	290 :"sic igitur debent venti quoque flamina ferri,",
	291 :"quae vel uti validum cum flumen procubuere",
	292 :"quam libet in partem, trudunt res ante ruuntque",
	293 :"impetibus crebris, inter dum vertice torto",
	294 :"corripiunt rapidique rotanti turbine portant.",
	295 :"quare etiam atque etiam sunt venti corpora caeca,",
	296 :"quandoquidem factis et moribus aemula magnis",
	297 :"amnibus inveniuntur, aperto corpore qui sunt.",
	298 :"Tum porro varios rerum sentimus odores",
	299 :"nec tamen ad naris venientis cernimus umquam",
	300 :"nec calidos aestus tuimur nec frigora quimus",
	301 :"usurpare oculis nec voces cernere suemus;",
	302 :"quae tamen omnia corporea constare necessest",
	303 :"natura, quoniam sensus inpellere possunt;",
	304 :"tangere enim et tangi, nisi corpus, nulla potest res.",
	305 :"Denique fluctifrago suspensae in litore vestis",
	306 :"uvescunt, eaedem dispansae in sole serescunt.",
	307 :"at neque quo pacto persederit umor aquai",
	308 :"visumst nec rursum quo pacto fugerit aestu.",
	309 :"in parvas igitur partis dispergitur umor,",
	310 :"quas oculi nulla possunt ratione videre.",
	311 :"quin etiam multis solis redeuntibus annis",
	312 :"anulus in digito subter tenuatur habendo,",
	313 :"stilicidi casus lapidem cavat, uncus aratri",
	314 :"ferreus occulte decrescit vomer in arvis,",
	315 :"strataque iam volgi pedibus detrita viarum",
	316 :"saxea conspicimus; tum portas propter aena",
	317 :"signa manus dextras ostendunt adtenuari",
	318 :"saepe salutantum tactu praeterque meantum.",
	319 :"haec igitur minui, cum sint detrita, videmus.",
	320 :"sed quae corpora decedant in tempore quoque,",
	321 :"invida praeclusit speciem natura videndi.",
	322 :"Postremo quae cumque dies naturaque rebus",
	323 :"paulatim tribuit moderatim crescere cogens,",
	324 :"nulla potest oculorum acies contenta tueri,",
	325 :"nec porro quae cumque aevo macieque senescunt,",
	326 :"nec, mare quae impendent, vesco sale saxa peresa",
	327 :"quid quoque amittant in tempore cernere possis.",
	328 :"corporibus caecis igitur natura gerit res.",
	329 :"Nec tamen undique corporea stipata tenentur",
	330 :"omnia natura; namque est in rebus inane.",
	331 :"quod tibi cognosse in multis erit utile rebus",
	332 :"nec sinet errantem dubitare et quaerere semper",
	333 :"de summa rerum et nostris diffidere dictis.",
	334 :"qua propter locus est intactus inane vacansque.",
	335 :"quod si non esset, nulla ratione moveri",
	336 :"res possent; namque officium quod corporis exstat,",
	337 :"officere atque obstare, id in omni tempore adesset",
	338 :"omnibus; haud igitur quicquam procedere posset,",
	339 :"principium quoniam cedendi nulla daret res.",
	340 :"at nunc per maria ac terras sublimaque caeli",
	341 :"multa modis multis varia ratione moveri",
	342 :"cernimus ante oculos, quae, si non esset inane,",
	343 :"non tam sollicito motu privata carerent",
	344 :"quam genita omnino nulla ratione fuissent,",
	345 :"undique materies quoniam stipata quiesset.",
	346 :"Praeterea quamvis solidae res esse putentur,",
	347 :"hinc tamen esse licet raro cum corpore cernas.",
	348 :"in saxis ac speluncis permanat aquarum",
	349 :"liquidus umor et uberibus flent omnia guttis.",
	350 :"dissipat in corpus sese cibus omne animantum;",
	351 :"crescunt arbusta et fetus in tempore fundunt,",
	352 :"quod cibus in totas usque ab radicibus imis",
	353 :"per truncos ac per ramos diffunditur omnis.",
	354 :"inter saepta meant voces et clausa domorum",
	355 :"transvolitant, rigidum permanat frigus ad ossa.",
	356 :"quod nisi inania sint, qua possent corpora quaeque",
	357 :"transire, haud ulla fieri ratione videres.",
	358 :"Denique cur alias aliis praestare videmus",
	359 :"pondere res rebus nihilo maiore figura?",
	360 :"nam si tantundemst in lanae glomere quantum",
	361 :"corporis in plumbo est, tantundem pendere par est,",
	362 :"corporis officiumst quoniam premere omnia deorsum,",
	363 :"contra autem natura manet sine pondere inanis.",
	364 :"ergo quod magnumst aeque leviusque videtur,",
	365 :"ni mirum plus esse sibi declarat inanis;",
	366 :"at contra gravius plus in se corporis esse",
	367 :"dedicat et multo vacui minus intus habere.",
	368 :"est igitur ni mirum id quod ratione sagaci",
	369 :"quaerimus, admixtum rebus, quod inane vocamus.",
	370 :"Illud in his rebus ne te deducere vero",
	371 :"possit, quod quidam fingunt, praecurrere cogor.",
	372 :"cedere squamigeris latices nitentibus aiunt",
	373 :"et liquidas aperire vias, quia post loca pisces",
	374 :"linquant, quo possint cedentes confluere undae;",
	375 :"sic alias quoque res inter se posse moveri",
	376 :"et mutare locum, quamvis sint omnia plena.",
	377 :"scilicet id falsa totum ratione receptumst.",
	378 :"nam quo squamigeri poterunt procedere tandem,",
	379 :"ni spatium dederint latices? concedere porro",
	380 :"quo poterunt undae, cum pisces ire nequibunt?",
	381 :"aut igitur motu privandumst corpora quaeque",
	382 :"aut esse admixtum dicundumst rebus inane,",
	383 :"unde initum primum capiat res quaeque movendi.",
	384 :"Postremo duo de concursu corpora lata",
	385 :"si cita dissiliant, nempe aer omne necessest,",
	386 :"inter corpora quod fiat, possidat inane.",
	387 :"is porro quamvis circum celerantibus auris",
	388 :"confluat, haud poterit tamen uno tempore totum",
	389 :"compleri spatium; nam primum quemque necessest",
	390 :"occupet ille locum, deinde omnia possideantur.",
	391 :"quod si forte aliquis, cum corpora dissiluere,",
	392 :"tum putat id fieri quia se condenseat aer,",
	393 :"errat; nam vacuum tum fit quod non fuit ante",
	394 :"et repletur item vacuum quod constitit ante,",
	395 :"nec tali ratione potest denserier aer",
	396 :"nec, si iam posset, sine inani posset, opinor,",
	397 :"ipse in se trahere et partis conducere in unum.",
	398 :"Qua propter, quamvis causando multa moreris,",
	399 :"esse in rebus inane tamen fateare necessest.",
	400 :"multaque praeterea tibi possum commemorando",
	401 :"argumenta fidem dictis conradere nostris.",
	402 :"verum animo satis haec vestigia parva sagaci",
	403 :"sunt, per quae possis cognoscere cetera tute.",
	404 :"namque canes ut montivagae persaepe ferai",
	405 :"naribus inveniunt intectas fronde quietes,",
	406 :"cum semel institerunt vestigia certa viai,",
	407 :"sic alid ex alio per te tute ipse videre",
	408 :"talibus in rebus poteris caecasque latebras",
	409 :"insinuare omnis et verum protrahere inde.",
	410 :"quod si pigraris paulumve recesseris ab re,",
	411 :"hoc tibi de plano possum promittere, Memmi:",
	412 :"usque adeo largos haustus e fontibus magnis",
	413 :"lingua meo suavis diti de pectore fundet,",
	414 :"ut verear ne tarda prius per membra senectus",
	415 :"serpat et in nobis vitai claustra resolvat,",
	416 :"quam tibi de quavis una re versibus omnis",
	417 :"argumentorum sit copia missa per auris.",
	418 :"Sed nunc ut repetam coeptum pertexere dictis,",
	419 :"omnis ut est igitur per se natura duabus",
	420 :"constitit in rebus; nam corpora sunt et inane,",
	421 :"haec in quo sita sunt et qua diversa moventur.",
	422 :"corpus enim per se communis dedicat esse",
	423 :"sensus; cui nisi prima fides fundata valebit,",
	424 :"haut erit occultis de rebus quo referentes",
	425 :"confirmare animi quicquam ratione queamus.",
	426 :"tum porro locus ac spatium, quod inane vocamus,",
	427 :"si nullum foret, haut usquam sita corpora possent",
	428 :"esse neque omnino quoquam diversa meare;",
	429 :"id quod iam supera tibi paulo ostendimus ante.",
	430 :"praeterea nihil est quod possis dicere ab omni",
	431 :"corpore seiunctum secretumque esse ab inani,",
	432 :"quod quasi tertia sit numero natura reperta.",
	433 :"nam quod cumque erit, esse aliquid debebit id ipsum",
	434 :"augmine vel grandi vel parvo denique, dum sit;",
	435 :"cui si tactus erit quamvis levis exiguusque,",
	436 :"corporis augebit numerum summamque sequetur;",
	437 :"sin intactile erit, nulla de parte quod ullam",
	438 :"rem prohibere queat per se transire meantem,",
	439 :"scilicet hoc id erit, vacuum quod inane vocamus.",
	440 :"Praeterea per se quod cumque erit, aut faciet quid",
	441 :"aut aliis fungi debebit agentibus ipsum",
	442 :"aut erit ut possint in eo res esse gerique.",
	443 :"at facere et fungi sine corpore nulla potest res",
	444 :"nec praebere locum porro nisi inane vacansque.",
	445 :"ergo praeter inane et corpora tertia per se",
	446 :"nulla potest rerum in numero natura relinqui,",
	447 :"nec quae sub sensus cadat ullo tempore nostros",
	448 :"nec ratione animi quam quisquam possit apisci.",
	449 :"Nam quae cumque cluent, aut his coniuncta duabus",
	450 :"rebus ea invenies aut horum eventa videbis.",
	451 :"coniunctum est id quod nusquam sine permitiali",
	452 :"discidio potis est seiungi seque gregari,",
	453 :"pondus uti saxis, calor ignis, liquor aquai,",
	454 :"tactus corporibus cunctis, intactus inani.",
	455 :"servitium contra paupertas divitiaeque,",
	456 :"libertas bellum concordia cetera quorum",
	457 :"adventu manet incolumis natura abituque,",
	458 :"haec soliti sumus, ut par est, eventa vocare.",
	459 :"tempus item per se non est, sed rebus ab ipsis",
	460 :"consequitur sensus, transactum quid sit in aevo,",
	461 :"tum quae res instet, quid porro deinde sequatur;",
	462 :"nec per se quemquam tempus sentire fatendumst",
	463 :"semotum ab rerum motu placidaque quiete.",
	464 :"denique Tyndaridem raptam belloque subactas",
	465 :"Troiiugenas gentis cum dicunt esse, videndumst",
	466 :"ne forte haec per se cogant nos esse fateri,",
	467 :"quando ea saecla hominum, quorum haec eventa fuerunt,",
	468 :"inrevocabilis abstulerit iam praeterita aetas;",
	469 :"namque aliud terris, aliud regionibus ipsis",
	470 :"eventum dici poterit quod cumque erit actum.",
	471 :"denique materies si rerum nulla fuisset",
	472 :"nec locus ac spatium, res in quo quaeque geruntur,",
	473 :"numquam Tyndaridis forma conflatus amore",
	474 :"ignis Alexandri Phrygio sub pectore gliscens",
	475 :"clara accendisset saevi certamina belli",
	476 :"nec clam durateus Troiianis Pergama partu",
	477 :"inflammasset equos nocturno Graiiugenarum;",
	478 :"perspicere ut possis res gestas funditus omnis",
	479 :"non ita uti corpus per se constare neque esse",
	480 :"nec ratione cluere eadem qua constet inane,",
	481 :"sed magis ut merito possis eventa vocare",
	482 :"corporis atque loci, res in quo quaeque gerantur.",
	483 :"Corpora sunt porro partim primordia rerum,",
	484 :"partim concilio quae constant principiorum.",
	485 :"sed quae sunt rerum primordia, nulla potest vis",
	486 :"stinguere; nam solido vincunt ea corpore demum.",
	487 :"etsi difficile esse videtur credere quicquam",
	488 :"in rebus solido reperiri corpore posse.",
	489 :"transit enim fulmen caeli per saepta domorum",
	490 :"clamor ut ac voces, ferrum candescit in igni",
	491 :"dissiliuntque fero ferventi saxa vapore;",
	492 :"cum labefactatus rigor auri solvitur aestu,",
	493 :"tum glacies aeris flamma devicta liquescit;",
	494 :"permanat calor argentum penetraleque frigus,",
	495 :"quando utrumque manu retinentes pocula rite",
	496 :"sensimus infuso lympharum rore superne.",
	497 :"usque adeo in rebus solidi nihil esse videtur.",
	498 :"sed quia vera tamen ratio naturaque rerum",
	499 :"cogit, ades, paucis dum versibus expediamus",
	500 :"esse ea quae solido atque aeterno corpore constent,",
	501 :"semina quae rerum primordiaque esse docemus,",
	502 :"unde omnis rerum nunc constet summa creata.",
	503 :"Principio quoniam duplex natura duarum",
	504 :"dissimilis rerum longe constare repertast,",
	505 :"corporis atque loci, res in quo quaeque geruntur,",
	506 :"esse utramque sibi per se puramque necessest.",
	507 :"nam qua cumque vacat spatium, quod inane vocamus,",
	508 :"corpus ea non est; qua porro cumque tenet se",
	509 :"corpus, ea vacuum nequaquam constat inane.",
	510 :"sunt igitur solida ac sine inani corpora prima.",
	511 :"Praeterea quoniam genitis in rebus inanest,",
	512 :"materiem circum solidam constare necessest;",
	513 :"nec res ulla potest vera ratione probari",
	514 :"corpore inane suo celare atque intus habere,",
	515 :"si non, quod cohibet, solidum constare relinquas.",
	516 :"id porro nihil esse potest nisi materiai",
	517 :"concilium, quod inane queat rerum cohibere.",
	518 :"materies igitur, solido quae corpore constat,",
	519 :"esse aeterna potest, cum cetera dissoluantur.",
	520 :"Tum porro si nil esset quod inane vocaret,",
	521 :"omne foret solidum; nisi contra corpora certa",
	522 :"essent quae loca complerent quae cumque tenerent",
	523 :"omne quod est spatium, vacuum constaret inane.",
	524 :"alternis igitur ni mirum corpus inani",
	525 :"distinctum, quoniam nec plenum naviter extat",
	526 :"nec porro vacuum; sunt ergo corpora certa,",
	527 :"quae spatium pleno possint distinguere inane.",
	528 :"haec neque dissolui plagis extrinsecus icta",
	529 :"possunt nec porro penitus penetrata retexi",
	530 :"nec ratione queunt alia temptata labare;",
	531 :"id quod iam supra tibi paulo ostendimus ante.",
	532 :"nam neque conlidi sine inani posse videtur",
	533 :"quicquam nec frangi nec findi in bina secando",
	534 :"nec capere umorem neque item manabile frigus",
	535 :"nec penetralem ignem, quibus omnia conficiuntur.",
	536 :"et quo quaeque magis cohibet res intus inane,",
	537 :"tam magis his rebus penitus temptata labascit.",
	538 :"ergo si solida ac sine inani corpora prima",
	539 :"sunt ita uti docui, sint haec aeterna necessest.",
	540 :"Praeterea nisi materies aeterna fuisset,",
	541 :"antehac ad nihilum penitus res quaeque redissent",
	542 :"de nihiloque renata forent quae cumque videmus.",
	543 :"at quoniam supra docui nil posse creari",
	544 :"de nihilo neque quod genitumst ad nil revocari,",
	545 :"esse inmortali primordia corpore debent,",
	546 :"dissolui quo quaeque supremo tempore possint,",
	547 :"materies ut subpeditet rebus reparandis.",
	548 :"sunt igitur solida primordia simplicitate",
	549 :"nec ratione queunt alia servata per aevom",
	550 :"ex infinito iam tempore res reparare.",
	551 :"denique si nullam finem natura parasset",
	552 :"frangendis rebus, iam corpora materiai",
	553 :"usque redacta forent aevo frangente priore,",
	554 :"ut nihil ex illis a certo tempore posset",
	555 :"conceptum summum aetatis pervadere finem.",
	556 :"nam quidvis citius dissolvi posse videmus",
	557 :"quam rursus refici; qua propter longa diei",
	558 :"infinita aetas ante acti temporis omnis",
	559 :"quod fregisset adhuc disturbans dissoluensque,",
	560 :"numquam relicuo reparari tempore posset.",
	561 :"at nunc ni mirum frangendi reddita finis",
	562 :"certa manet, quoniam refici rem quamque videmus",
	563 :"et finita simul generatim tempora rebus",
	564 :"stare, quibus possint aevi contingere florem.",
	565 :"Huc accedit uti, solidissima materiai",
	566 :"corpora cum constant, possint tamen omnia reddi,",
	567 :"mollia quae fiunt, aer aqua terra vapores,",
	568 :"quo pacto fiant et qua vi quaeque gerantur,",
	569 :"admixtum quoniam semel est in rebus inane.",
	570 :"at contra si mollia sint primordia rerum,",
	571 :"unde queant validi silices ferrumque creari,",
	572 :"non poterit ratio reddi; nam funditus omnis",
	573 :"principio fundamenti natura carebit.",
	574 :"sunt igitur solida pollentia simplicitate,",
	575 :"quorum condenso magis omnia conciliatu",
	576 :"artari possunt validasque ostendere viris.",
	577 :"porro si nullast frangendis reddita finis",
	578 :"corporibus, tamen ex aeterno tempore quaeque",
	579 :"nunc etiam superare necessest corpora rebus,",
	580 :"quae non dum clueant ullo temptata periclo.",
	581 :"at quoniam fragili natura praedita constant,",
	582 :"discrepat aeternum tempus potuisse manere",
	583 :"innumerabilibus plagis vexata per aevom.",
	584 :"Denique iam quoniam generatim reddita finis",
	585 :"crescendi rebus constat vitamque tenendi,",
	586 :"et quid quaeque queant per foedera naturai,",
	587 :"quid porro nequeant, sancitum quando quidem extat,",
	588 :"nec commutatur quicquam, quin omnia constant",
	589 :"usque adeo, variae volucres ut in ordine cunctae",
	590 :"ostendant maculas generalis corpore inesse,",
	591 :"inmutabilis materiae quoque corpus habere",
	592 :"debent ni mirum; nam si primordia rerum",
	593 :"commutari aliqua possent ratione revicta,",
	594 :"incertum quoque iam constet quid possit oriri,",
	595 :"quid nequeat, finita potestas denique cuique",
	596 :"qua nam sit ratione atque alte terminus haerens,",
	597 :"nec totiens possent generatim saecla referre",
	598 :"naturam mores victum motusque parentum.",
	599 :"Tum porro quoniam est extremum quodque cacumen",
	600 :"corporis illius, quod nostri cernere sensus",
	601 :"iam nequeunt, id ni mirum sine partibus extat",
	602 :"et minima constat natura nec fuit umquam",
	603 :"per se secretum neque post hac esse valebit,",
	604 :"alterius quoniamst ipsum pars primaque et una,",
	605 :"inde aliae atque aliae similes ex ordine partes",
	606 :"agmine condenso naturam corporis explent;",
	607 :"quae quoniam per se nequeunt constare, necessest",
	608 :"haerere unde queant nulla ratione revelli.",
	609 :"sunt igitur solida primordia simplicitate,",
	610 :"quae minimis stipata cohaerent partibus arte.",
	611 :"non ex illorum conventu conciliata,",
	612 :"sed magis aeterna pollentia simplicitate,",
	613 :"unde neque avelli quicquam neque deminui iam",
	614 :"concedit natura reservans semina rebus.",
	615 :"Praeterea nisi erit minimum, parvissima quaeque",
	616 :"corpora constabunt ex partibus infinitis,",
	617 :"quippe ubi dimidiae partis pars semper habebit",
	618 :"dimidiam partem nec res praefiniet ulla.",
	619 :"ergo rerum inter summam minimamque quod escit,",
	620 :"nil erit ut distet; nam quamvis funditus omnis",
	621 :"summa sit infinita, tamen, parvissima quae sunt,",
	622 :"ex infinitis constabunt partibus aeque.",
	623 :"quod quoniam ratio reclamat vera negatque",
	624 :"credere posse animum, victus fateare necessest",
	625 :"esse ea quae nullis iam praedita partibus extent",
	626 :"et minima constent natura. quae quoniam sunt,",
	627 :"illa quoque esse tibi solida atque aeterna fatendum.",
	628 :"Denique si minimas in partis cuncta resolvi",
	629 :"cogere consuesset rerum natura creatrix,",
	630 :"iam nihil ex illis eadem reparare valeret",
	631 :"propterea quia, quae nullis sunt partibus aucta,",
	632 :"non possunt ea quae debet genitalis habere",
	633 :"materies, varios conexus pondera plagas",
	634 :"concursus motus, per quas res quaeque geruntur.",
	635 :"Quapropter qui materiem rerum esse putarunt",
	636 :"ignem atque ex igni summam consistere solo,",
	637 :"magno opere a vera lapsi ratione videntur.",
	638 :"Heraclitus init quorum dux proelia primus,",
	639 :"clarus <ob> obscuram linguam magis inter inanis",
	640 :"quamde gravis inter Graios, qui vera requirunt;",
	641 :"omnia enim stolidi magis admirantur amantque,",
	642 :"inversis quae sub verbis latitantia cernunt,",
	643 :"veraque constituunt quae belle tangere possunt",
	644 :"auris et lepido quae sunt fucata sonore.",
	645 :"Nam cur tam variae res possent esse, requiro,",
	646 :"ex uno si sunt igni puroque creatae?",
	647 :"nil prodesset enim calidum denserier ignem",
	648 :"nec rare fieri, si partes ignis eandem",
	649 :"naturam quam totus habet super ignis haberent.",
	650 :"acrior ardor enim conductis partibus esset,",
	651 :"languidior porro disiectis <dis>que supatis.",
	652 :"amplius hoc fieri nihil est quod posse rearis",
	653 :"talibus in causis, ne dum variantia rerum",
	654 :"tanta queat densis rarisque ex ignibus esse.",
	655 :"Id quoque: si faciant admixtum rebus inane,",
	656 :"denseri poterunt ignes rarique relinqui;",
	657 :"sed quia multa sibi cernunt contraria quae sint",
	658 :"et fugitant in rebus inane relinquere purum,",
	659 :"ardua dum metuunt, amittunt vera viai",
	660 :"nec rursum cernunt exempto rebus inane",
	661 :"omnia denseri fierique ex omnibus unum",
	662 :"corpus, nil ab se quod possit mittere raptim,",
	663 :"aestifer ignis uti lumen iacit atque vaporem,",
	664 :"ut videas non e stipatis partibus esse.",
	665 :"Quod si forte alia credunt ratione potesse",
	666 :"ignis in coetu stingui mutareque corpus,",
	667 :"scilicet ex nulla facere id si parte reparcent,",
	668 :"occidet ad nihilum ni mirum funditus ardor",
	669 :"omnis et <e> nihilo fient quae cumque creantur;",
	670 :"nam quod cumque suis mutatum finibus exit,",
	671 :"continuo hoc mors est illius quod fuit ante.",
	672 :"proinde aliquid superare necesse est incolume ollis,",
	673 :"ne tibi res redeant ad nilum funditus omnes",
	674 :"de nihiloque renata vigescat copia rerum.",
	675 :"Nunc igitur quoniam certissima corpora quaedam",
	676 :"sunt, quae conservant naturam semper eandem,",
	677 :"quorum abitu aut aditu mutatoque ordine mutant",
	678 :"naturam res et convertunt corpora sese,",
	679 :"scire licet non esse haec ignea corpora rerum.",
	680 :"nil referret enim quaedam decedere, abire",
	681 :"atque alia adtribui mutarique ordine quaedam,",
	682 :"si tamen ardoris naturam cuncta tenerent;",
	683 :"ignis enim foret omnimodis quod cumque crearet.",
	684 :"verum, ut opinor, itast: sunt quaedam corpora, quorum",
	685 :"concursus motus ordo positura figurae",
	686 :"efficiunt ignis mutatoque ordine mutant",
	687 :"naturam neque sunt igni simulata neque ulli",
	688 :"praeterea rei quae corpora mittere possit",
	689 :"sensibus et nostros adiectu tangere tactus.",
	690 :"dicere porro ignem res omnis esse neque ullam",
	691 :"rem veram in numero rerum constare nisi ignem,",
	692 :"quod facit hic idem, perdelirum esse videtur.",
	693 :"nam contra sensus ab sensibus ipse repugnat",
	694 :"et labefactat eos, unde omnia credita pendent,",
	695 :"unde hic cognitus est ipsi quem nominat ignem;",
	696 :"credit enim sensus ignem cognoscere vere,",
	697 :"cetera non credit, quae nilo clara minus sunt.",
	698 :"quod mihi cum vanum tum delirum esse videtur;",
	699 :"quo referemus enim? quid nobis certius ipsis",
	700 :"sensibus esse potest, qui vera ac falsa notemus?",
	701 :"Praeterea quare quisquam magis omnia tollat",
	702 :"et velit ardoris naturam linquere solam,",
	703 :"quam neget esse ignis, <aliam> tamen esse relinquat?",
	704 :"aequa videtur enim dementia dicere utrumque.",
	705 :"Quapropter qui materiem rerum esse putarunt",
	706 :"ignem atque ex igni summam consistere posse,",
	707 :"et qui principium gignundis aera rebus",
	708 :"constituere aut umorem qui cumque putarunt",
	709 :"fingere res ipsum per se terramve creare",
	710 :"omnia et in rerum naturas vertier omnis,",
	711 :"magno opere a vero longe derrasse videntur.",
	712 :"adde etiam qui conduplicant primordia rerum",
	713 :"aera iungentes igni terramque liquori,",
	714 :"et qui quattuor ex rebus posse omnia rentur",
	715 :"ex igni terra atque anima procrescere et imbri.",
	716 :"quorum Acragantinus cum primis Empedocles est,",
	717 :"insula quem triquetris terrarum gessit in oris,",
	718 :"quam fluitans circum magnis anfractibus aequor",
	719 :"Ionium glaucis aspargit virus ab undis",
	720 :"angustoque fretu rapidum mare dividit undis",
	721 :"Aeoliae terrarum oras a finibus eius.",
	722 :"hic est vasta Charybdis et hic Aetnaea minantur",
	723 :"murmura flammarum rursum se colligere iras,",
	724 :"faucibus eruptos iterum vis ut vomat ignis",
	725 :"ad caelumque ferat flammai fulgura rursum.",
	726 :"quae cum magna modis multis miranda videtur",
	727 :"gentibus humanis regio visendaque fertur",
	728 :"rebus opima bonis, multa munita virum vi,",
	729 :"nil tamen hoc habuisse viro praeclarius in se",
	730 :"nec sanctum magis et mirum carumque videtur.",
	731 :"carmina quin etiam divini pectoris eius",
	732 :"vociferantur et exponunt praeclara reperta,",
	733 :"ut vix humana videatur stirpe creatus.",
	734 :"Hic tamen et supra quos diximus inferiores",
	735 :"partibus egregie multis multoque minores,",
	736 :"quamquam multa bene ac divinitus invenientes",
	737 :"ex adyto tam quam cordis responsa dedere",
	738 :"sanctius et multo certa ratione magis quam",
	739 :"Pythia quae tripodi a Phoebi lauroque profatur,",
	740 :"principiis tamen in rerum fecere ruinas",
	741 :"et graviter magni magno cecidere ibi casu.",
	742 :"Primum quod motus exempto rebus inani",
	743 :"constituunt et res mollis rarasque relinquunt",
	744 :"aera solem ignem terras animalia frugis",
	745 :"nec tamen admiscent in eorum corpus inane;",
	746 :"deinde quod omnino finem non esse secandis",
	747 :"corporibus facient neque pausam stare fragori",
	748 :"nec prorsum in rebus minimum consistere qui<cquam>,",
	749 :"cum videamus id extremum cuiusque cacumen",
	750 :"esse quod ad sensus nostros minimum esse videtur,",
	751 :"conicere ut possis ex hoc, quae cernere non quis",
	752 :"extremum quod habent, minimum consistere <rerum>.",
	753 :"Huc accedit item, quoniam primordia rerum",
	754 :"mollia constituunt, quae nos nativa videmus",
	755 :"esse et mortali cum corpore, funditus ut qui",
	756 :"debeat ad nihilum iam rerum summa reverti",
	757 :"de nihiloque renata vigescere copia rerum;",
	758 :"quorum utrumque quid a vero iam distet habebis.",
	759 :"Deinde inimica modis multis sunt atque veneno",
	760 :"ipsa sibi inter se; quare aut congressa peribunt",
	761 :"aut ita diffugient, ut tempestate coacta",
	762 :"fulmina diffugere atque imbris ventosque videmus.",
	763 :"Denique quattuor ex rebus si cuncta creantur",
	764 :"atque in eas rursum res omnia dissoluuntur,",
	765 :"qui magis illa queunt rerum primordia dici",
	766 :"quam contra res illorum retroque putari?",
	767 :"alternis gignuntur enim mutantque colorem",
	768 :"et totam inter se naturam tempore ab omni.",
	769 :"[fulmina diffugere atque imbris ventosque videmus.]",
	770 :"sin ita forte putas ignis terraeque coire",
	771 :"corpus et aerias auras roremque liquoris,",
	772 :"nil in concilio naturam ut mutet eorum,",
	773 :"nulla tibi ex illis poterit res esse creata,",
	774 :"non animans, non exanimo cum corpore, ut arbos;",
	775 :"quippe suam quicque in coetu variantis acervi",
	776 :"naturam ostendet mixtusque videbitur aer",
	777 :"cum terra simul et quodam cum rore manere.",
	778 :"at primordia gignundis in rebus oportet",
	779 :"naturam clandestinam caecamque adhibere,",
	780 :"emineat ne quid, quod contra pugnet et obstet",
	781 :"quo minus esse queat proprie quodcumque creatur.",
	782 :"Quin etiam repetunt a caelo atque ignibus eius",
	783 :"et primum faciunt ignem se vertere in auras",
	784 :"aeris, hinc imbrem gigni terramque creari",
	785 :"ex imbri retroque a terra cuncta reverti,",
	786 :"umorem primum, post aera, deinde calorem,",
	787 :"nec cessare haec inter se mutare, meare",
	788 :"a caelo ad terram, de terra ad sidera mundi.",
	789 :"quod facere haud ullo debent primordia pacto.",
	790 :"immutabile enim quiddam superare necessest,",
	791 :"ne res ad nihilum redigantur funditus omnes;",
	792 :"nam quod cumque suis mutatum finibus exit,",
	793 :"continuo hoc mors est illius quod fuit ante.",
	794 :"quapropter quoniam quae paulo diximus ante",
	795 :"in commutatum veniunt, constare necessest",
	796 :"ex aliis ea, quae nequeant convertier usquam,",
	797 :"ne tibi res redeant ad nilum funditus omnis;",
	798 :"quin potius tali natura praedita quaedam",
	799 :"corpora constituas, ignem si forte crearint,",
	800 :"posse eadem demptis paucis paucisque tributis,",
	801 :"ordine mutato et motu, facere aeris auras,",
	802 :"sic alias aliis rebus mutarier omnis?",
	803 :"'At manifesta palam res indicat' inquis 'in auras",
	804 :"aeris e terra res omnis crescere alique;",
	805 :"et nisi tempestas indulget tempore fausto",
	806 :"imbribus, ut tabe nimborum arbusta vacillent,",
	807 :"solque sua pro parte fovet tribuitque calorem,",
	808 :"crescere non possint fruges arbusta animantis.'",
	809 :"scilicet et nisi nos cibus aridus et tener umor",
	810 :"adiuvet, amisso iam corpore vita quoque omnis",
	811 :"omnibus e nervis atque ossibus exsoluatur;",
	812 :"adiutamur enim dubio procul atque alimur nos",
	813 :"certis ab rebus, certis aliae atque aliae res.",
	814 :"ni mirum quia multa modis communia multis",
	815 :"multarum rerum in rebus primordia mixta",
	816 :"sunt, ideo variis variae res rebus aluntur.",
	817 :"atque eadem magni refert primordia saepe",
	818 :"cum quibus et quali positura contineantur",
	819 :"et quos inter se dent motus accipiantque;",
	820 :"namque eadem caelum mare terras flumina solem",
	821 :"constituunt, eadem fruges arbusta animantis,",
	822 :"verum aliis alioque modo commixta moventur.",
	823 :"quin etiam passim nostris in versibus ipsis",
	824 :"multa elementa vides multis communia verbis,",
	825 :"cum tamen inter se versus ac verba necessest",
	826 :"confiteare et re et sonitu distare sonanti.",
	827 :"tantum elementa queunt permutato ordine solo;",
	828 :"at rerum quae sunt primordia, plura adhibere",
	829 :"possunt unde queant variae res quaeque creari.",
	830 :"Nunc et Anaxagorae scrutemur homoeomerian",
	831 :"quam Grai memorant nec nostra dicere lingua",
	832 :"concedit nobis patrii sermonis egestas,",
	833 :"sed tamen ipsam rem facilest exponere verbis.",
	834 :"principio, rerum quam dicit homoeomerian,",
	835 :"ossa videlicet e pauxillis atque minutis",
	836 :"ossibus hic et de pauxillis atque minutis",
	837 :"visceribus viscus gigni sanguenque creari",
	838 :"sanguinis inter se multis coeuntibus guttis",
	839 :"ex aurique putat micis consistere posse",
	840 :"aurum et de terris terram concrescere parvis,",
	841 :"ignibus ex ignis, umorem umoribus esse,",
	842 :"cetera consimili fingit ratione putatque.",
	843 :"nec tamen esse ulla de parte in rebus inane",
	844 :"concedit neque corporibus finem esse secandis.",
	845 :"quare in utraque mihi pariter ratione videtur",
	846 :"errare atque illi, supra quos diximus ante.",
	847 :"Adde quod inbecilla nimis primordia fingit;",
	848 :"si primordia sunt, simili quae praedita constant",
	849 :"natura atque ipsae res sunt aequeque laborant",
	850 :"et pereunt, neque ab exitio res ulla refrenat.",
	851 :"nam quid in oppressu valido durabit eorum,",
	852 :"ut mortem effugiat, leti sub dentibus ipsis?",
	853 :"ignis an umor an aura? quid horum? sanguen an ossa?",
	854 :"nil ut opinor, ubi ex aequo res funditus omnis",
	855 :"tam mortalis erit quam quae manifesta videmus",
	856 :"ex oculis nostris aliqua vi victa perire.",
	857 :"at neque reccidere ad nihilum res posse neque autem",
	858 :"crescere de nihilo testor res ante probatas.",
	859 :"Praeterea quoniam cibus auget corpus alitque,",
	860 :"scire licet nobis venas et sanguen et ossa",
	861 :"* * *860a",
	862 :"sive cibos omnis commixto corpore dicent",
	863 :"esse et habere in se nervorum corpora parva",
	864 :"ossaque et omnino venas partisque cruoris,",
	865 :"fiet uti cibus omnis et aridus et liquor ipse",
	866 :"ex alienigenis rebus constare putetur,",
	867 :"ossibus et nervis sanieque et sanguine mixto.",
	868 :"Praeterea quae cumque e terra corpora crescunt,",
	869 :"si sunt in terris, terram constare necessest",
	870 :"ex alienigenis, quae terris exoriuntur.",
	871 :"transfer item, totidem verbis utare licebit:",
	872 :"in lignis si flamma latet fumusque cinisque,",
	873 :"ex alienigenis consistant ligna necessest,",
	874 :"[praeterea tellus quae corpora cumque alit auget]",
	875 :"ex alienigenis, quae lignis <ex>oriuntur.",
	876 :"Linquitur hic quaedam latitandi copia tenvis,",
	877 :"id quod Anaxagoras sibi sumit, ut omnibus omnis",
	878 :"res putet inmixtas rebus latitare, sed illud",
	879 :"apparere unum, cuius sint plurima mixta",
	880 :"et magis in promptu primaque in fronte locata.",
	881 :"quod tamen a vera longe ratione repulsumst;",
	882 :"conveniebat enim fruges quoque saepe, minaci",
	883 :"robore cum in saxi franguntur, mittere signum",
	884 :"sanguinis aut aliquid, nostro quae corpore aluntur.",
	885 :"cum lapidi in lapidem terimus, manare cruorem",
	886 :"consimili ratione herbis quoque saepe decebat,",
	887 :"et latices dulcis guttas similique sapore",
	888 :"mittere, lanigerae quali sunt ubere lactis,",
	889 :"scilicet et glebis terrarum saepe friatis",
	890 :"herbarum genera et fruges frondesque videri",
	891 :"dispertita inter terram latitare minute,",
	892 :"postremo in lignis cinerem fumumque videri,",
	893 :"cum praefracta forent, ignisque latere minutos.",
	894 :"quorum nil fieri quoniam manifesta docet res,",
	895 :"scire licet non esse in rebus res ita mixtas,",
	896 :"verum semina multimodis inmixta latere",
	897 :"multarum rerum in rebus communia debent.",
	898 :"'At saepe in magnis fit montibus' inquis 'ut altis",
	899 :"arboribus vicina cacumina summa terantur",
	900 :"inter se validis facere id cogentibus austris,",
	901 :"donec flammai fulserunt flore coorto.'",
	902 :"scilicet et non est lignis tamen insitus ignis,",
	903 :"verum semina sunt ardoris multa, terendo",
	904 :"quae cum confluxere, creant incendia silvis.",
	905 :"quod si facta foret silvis abscondita flamma,",
	906 :"non possent ullum tempus celarier ignes,",
	907 :"conficerent volgo silvas, arbusta cremarent.",
	908 :"iamne vides igitur, paulo quod diximus ante,",
	909 :"permagni referre eadem primordia saepe",
	910 :"cum quibus et quali positura contineantur",
	911 :"et quos inter se dent motus accipiantque,",
	912 :"atque eadem paulo inter se mutata creare",
	913 :"ignes et lignum? quo pacto verba quoque ipsa",
	914 :"inter se paulo mutatis sunt elementis,",
	915 :"cum ligna atque ignes distincta voce notemus.",
	916 :"Denique iam quae cumque in rebus cernis apertis",
	917 :"si fieri non posse putas, quin materiai",
	918 :"corpora consimili natura praedita fingas,",
	919 :"hac ratione tibi pereunt primordia rerum:",
	920 :"fiet uti risu tremulo concussa cachinnent",
	921 :"et lacrimis salsis umectent ora genasque.",
	922 :"Nunc age, quod super est, cognosce et clarius audi.",
	923 :"nec me animi fallit quam sint obscura; sed acri",
	924 :"percussit thyrso laudis spes magna meum cor",
	925 :"et simul incussit suavem mi in pectus amorem",
	926 :"Musarum, quo nunc instinctus mente vigenti",
	927 :"avia Pieridum peragro loca nullius ante",
	928 :"trita solo. iuvat integros accedere fontis",
	929 :"atque haurire iuvatque novos decerpere flores",
	930 :"insignemque meo capiti petere inde coronam,",
	931 :"unde prius nulli velarint tempora Musae;",
	932 :"primum quod magnis doceo de rebus et artis",
	933 :"religionum animum nodis exsolvere pergo,",
	934 :"deinde quod obscura de re tam lucida pango",
	935 :"carmina musaeo contingens cuncta lepore.",
	936 :"id quoque enim non ab nulla ratione videtur;",
	937 :"sed vel uti pueris absinthia taetra medentes",
	938 :"cum dare conantur, prius oras pocula circum",
	939 :"contingunt mellis dulci flavoque liquore,",
	940 :"ut puerorum aetas inprovida ludificetur",
	941 :"labrorum tenus, interea perpotet amarum",
	942 :"absinthi laticem deceptaque non capiatur,",
	943 :"sed potius tali facto recreata valescat,",
	944 :"sic ego nunc, quoniam haec ratio plerumque videtur",
	945 :"tristior esse quibus non est tractata, retroque",
	946 :"volgus abhorret ab hac, volui tibi suaviloquenti",
	947 :"carmine Pierio rationem exponere nostram",
	948 :"et quasi musaeo dulci contingere melle,",
	949 :"si tibi forte animum tali ratione tenere",
	950 :"versibus in nostris possem, dum perspicis omnem",
	951 :"naturam rerum, qua constet compta figura.",
	952 :"Sed quoniam docui solidissima materiai",
	953 :"corpora perpetuo volitare invicta per aevom,",
	954 :"nunc age, summai quaedam sit finis eorum",
	955 :"nec<ne> sit, evolvamus; item quod inane repertumst",
	956 :"seu locus ac spatium, res in quo quaeque gerantur,",
	957 :"pervideamus utrum finitum funditus omne",
	958 :"constet an immensum pateat vasteque profundum.",
	959 :"Omne quod est igitur nulla regione viarum",
	960 :"finitumst; namque extremum debebat habere.",
	961 :"extremum porro nullius posse videtur",
	962 :"esse, nisi ultra sit quod finiat, ut videatur",
	963 :"quo non longius haec sensus natura sequatur.",
	964 :"nunc extra summam quoniam nihil esse fatendum,",
	965 :"non habet extremum, caret ergo fine modoque.",
	966 :"nec refert quibus adsistas regionibus eius;",
	967 :"usque adeo, quem quisque locum possedit, in omnis",
	968 :"tantundem partis infinitum omne relinquit.",
	969 :"Praeterea si iam finitum constituatur",
	970 :"omne quod est spatium, si quis procurrat ad oras",
	971 :"ultimus extremas iaciatque volatile telum,",
	972 :"id validis utrum contortum viribus ire",
	973 :"quo fuerit missum mavis longeque volare,",
	974 :"an prohibere aliquid censes obstareque posse?",
	975 :"alterutrum fatearis enim sumasque necessest.",
	976 :"quorum utrumque tibi effugium praecludit et omne",
	977 :"cogit ut exempta concedas fine patere.",
	978 :"nam sive est aliquid quod probeat efficiatque",
	979 :"quo minus quo missum est veniat finique locet se,",
	980 :"sive foras fertur, non est a fine profectum.",
	981 :"hoc pacto sequar atque, oras ubi cumque locaris",
	982 :"extremas, quaeram: quid telo denique fiet?",
	983 :"fiet uti nusquam possit consistere finis",
	984 :"effugiumque fugae prolatet copia semper.",
	985 :"Praeterea spatium summai totius omne",
	986 :"undique si inclusum certis consisteret oris",
	987 :"finitumque foret, iam copia materiai",
	988 :"undique ponderibus solidis confluxet ad imum",
	989 :"nec res ulla geri sub caeli tegmine posset",
	990 :"nec foret omnino caelum neque lumina solis,",
	991 :"quippe ubi materies omnis cumulata iaceret",
	992 :"ex infinito iam tempore subsidendo.",
	993 :"at nunc ni mirum requies data principiorum",
	994 :"corporibus nullast, quia nil est funditus imum,",
	995 :"quo quasi confluere et sedes ubi ponere possint.",
	996 :"semper in adsiduo motu res quaeque geruntur",
	997 :"partibus <in> cunctis, infernaque suppeditantur",
	998 :"ex infinito cita corpora materiai.",
	999 :"Postremo ante oculos res rem finire videtur;",
	1000 :"aer dissaepit collis atque aera montes,",
	1001 :"terra mare et contra mare terras terminat omnis;",
	1002 :"omne quidem vero nihil est quod finiat extra.",
	1003 :"est igitur natura loci spatiumque profundi,",
	1004 :"quod neque clara suo percurrere fulmina cursu",
	1005 :"perpetuo possint aevi labentia tractu",
	1006 :"nec prorsum facere ut restet minus ire meando;",
	1007 :"usque adeo passim patet ingens copia rebus",
	1008 :"finibus exemptis in cunctas undique partis.",
	1009 :"Ipsa modum porro sibi rerum summa parare",
	1010 :"ne possit, natura tenet, quae corpus inane",
	1011 :"et quod inane autem est finiri corpore cogit,",
	1012 :"ut sic alternis infinita omnia reddat,",
	1013 :"aut etiam alterutrum, nisi terminet alterum eorum,",
	1014 :"simplice natura pateat tamen inmoderatum,",
	1015 :"nec mare nec tellus neque caeli lucida templa",
	1016 :"nec mortale genus nec divum corpora sancta",
	1017 :"exiguum possent horai sistere tempus;",
	1018 :"nam dispulsa suo de coetu materiai",
	1019 :"copia ferretur magnum per inane soluta,",
	1020 :"sive adeo potius numquam concreta creasset",
	1021 :"ullam rem, quoniam cogi disiecta nequisset.",
	1022 :"nam certe neque consilio primordia rerum",
	1023 :"ordine se suo quaeque sagaci mente locarunt",
	1024 :"nec quos quaeque <darent motus pepigere profecto>",
	1025 :"sed quia multa modis multis mutata per omne",
	1026 :"ex infinito vexantur percita plagis,",
	1027 :"omne genus motus et coetus experiundo",
	1028 :"tandem deveniunt in talis disposituras,",
	1029 :"qualibus haec rerum consistit summa creata,",
	1030 :"et multos etiam magnos servata per annos",
	1031 :"ut semel in motus coniectast convenientis,",
	1032 :"efficit ut largis avidum mare fluminis undis",
	1033 :"integrent amnes et solis terra vapore",
	1034 :"fota novet fetus summissaque gens animantum",
	1035 :"floreat et vivant labentis aetheris ignes.",
	1036 :"quod nullo facerent pacto, nisi materiai",
	1037 :"ex infinito suboriri copia posset,",
	1038 :"unde amissa solent reparare in tempore quaeque.",
	1039 :"nam vel uti privata cibo natura animantum",
	1040 :"diffluit amittens corpus, sic omnia debent",
	1041 :"dissolui simul ac defecit suppeditare",
	1042 :"materies aliqua ratione aversa viai.",
	1043 :"nec plagae possunt extrinsecus undique summam",
	1044 :"conservare omnem, quae cumque est conciliata.",
	1045 :"cudere enim crebro possunt partemque morari,",
	1046 :"dum veniant aliae ac suppleri summa queatur;",
	1047 :"inter dum resilire tamen coguntur et una",
	1048 :"principiis rerum spatium tempusque fugai",
	1049 :"largiri, ut possint a coetu libera ferri.",
	1050 :"quare etiam atque etiam suboriri multa necessest,",
	1051 :"et tamen ut plagae quoque possint suppetere ipsae,",
	1052 :"infinita opus est vis undique materiai.",
	1053 :"Illud in his rebus longe fuge credere, Memmi,",
	1054 :"in medium summae quod dicunt omnia niti",
	1055 :"atque ideo mundi naturam stare sine ullis",
	1056 :"ictibus externis neque quoquam posse resolvi",
	1057 :"summa atque ima, quod in medium sint omnia nixa,",
	1058 :"ipsum si quicquam posse in se sistere credis,",
	1059 :"et quae pondera sunt sub terris omnia sursum",
	1060 :"nitier in terraque retro requiescere posta,",
	1061 :"ut per aquas quae nunc rerum simulacra videmus;",
	1062 :"et simili ratione animalia suppa vagari",
	1063 :"contendunt neque posse e terris in loca caeli",
	1064 :"reccidere inferiora magis quam corpora nostra",
	1065 :"sponte sua possint in caeli templa volare;",
	1066 :"illi cum videant solem, nos sidera noctis",
	1067 :"cernere et alternis nobiscum tempora caeli",
	1068 :"dividere et noctes parilis agitare diebus.",
	1069 :"sed vanus stolidis haec * * *",
	1070 :"amplexi quod habent perv * * *",
	1071 :"nam medium nihil esse potest * * *",
	1072 :"infinita; neque omnino, si iam <medium sit>,",
	1073 :"possit ibi quicquam consistere * * *",
	1074 :"quam quavis alia longe ratione * * *",
	1075 :"omnis enim locus ac spatium, quod in<ane vocamus>,",
	1076 :"per medium, per non medium, concedere <debet>",
	1077 :"aeque ponderibus, motus qua cumque feruntur.",
	1078 :"nec quisquam locus est, quo corpora cum venerunt,",
	1079 :"ponderis amissa vi possint stare <in> inani;",
	1080 :"nec quod inane autem est ulli subsistere debet,",
	1081 :"quin, sua quod natura petit, concedere pergat.",
	1082 :"haud igitur possunt tali ratione teneri",
	1083 :"res in concilium medii cuppedine victae.",
	1084 :"Praeterea quoniam non omnia corpora fingunt",
	1085 :"in medium niti, sed terrarum atque liquoris",
	1086 :"umorem ponti magnasque e montibus undas,",
	1087 :"et quasi terreno quae corpore contineantur,",
	1088 :"at contra tenuis exponunt aeris auras",
	1089 :"et calidos simul a medio differrier ignis,",
	1090 :"atque ideo totum circum tremere aethera signis",
	1091 :"et solis flammam per caeli caerula pasci,",
	1092 :"quod calor a medio fugiens se ibi conligat omnis,",
	1093 :"nec prorsum arboribus summos frondescere ramos",
	1094 :"posse, nisi a terris paulatim cuique cibatum",
	1095 :"ne volucri ritu flammarum moenia mundi",
	1096 :"diffugiant subito magnum per inane soluta",
	1097 :"et ne cetera consimili ratione sequantur",
	1098 :"neve ruant caeli tonitralia templa superne",
	1099 :"terraque se pedibus raptim subducat et omnis",
	1100 :"inter permixtas rerum caelique ruinas",
	1101 :"corpora solventes abeat per inane profundum,",
	1102 :"temporis ut puncto nihil extet reliquiarum",
	1103 :"desertum praeter spatium et primordia caeca.",
	1104 :"nam qua cumque prius de parti corpora desse",
	1105 :"constitues, haec rebus erit pars ianua leti,",
	1106 :"hac se turba foras dabit omnis materiai.",
	1107 :"Haec sic pernosces parva perductus opella;",
	1108 :"namque alid ex alio clarescet nec tibi caeca",
	1109 :"nox iter eripiet, quin ultima naturai",
	1110 :"pervideas: ita res accendent lumina rebus."
};

console.log(arrayRerum);

$(document).ready(function(){
	$("#buttonRerum").click(function(){
		valoreIniziale = document.getElementById("idRerum0").value;
		valoreFinale = document.getElementById("idRerum1").value;

		rangeRerum=parseInt(valoreFinale, 10)-parseInt(valoreIniziale, 10)+1;

		numero=Math.ceil(Math.random()*rangeRerum);

		console.log("Range: "+rangeRerum);

		console.log(numero);

		//randno=array1[numero];

		randno="";

		for (let i = 0; i < 15; i++) {
			if (typeof(arrayRerum[numero+i])=="undefined") {
				arrayRerum[numero+i]="..."
			}
			randno+=arrayRerum[numero+i]+"\n";
		}

		$('#zonaDinamicaVerso').text("Verso iniziale numero: "+numero);

		$('#zonaDinamicaNow').text(randno);
	});
});