var arrayEneide = {
	1 :"Sic fatur lacrimans, classique immittit habenas",
	2 :"et tandem Euboicis Cumarum adlabitur oris.",
	3 :"obuertunt pelago proras; tum dente tenaci",
	4 :"ancora fundabat nauis et litora curuae",
	5 :"praetexunt puppes. iuuenum manus emicat ardens",
	6 :"litus in Hesperium; quaerit pars semina flammae",
	7 :"abstrusa in uenis silicis, pars densa ferarum",
	8 :"tecta rapit siluas inuentaque flumina monstrat.",
	9 :"at pius Aeneas arces quibus altus Apollo",
	10 :"praesidet horrendaeque procul secreta Sibyllae,",
	11 :"antrum immane, petit, magnam cui mentem animumque",
	12 :"Delius inspirat uates aperitque futura.",
	13 :"iam subeunt Triuiae lucos atque aurea tecta.",
	14 :"Daedalus, ut fama est, fugiens Minoia regna",
	15 :"praepetibus pennis ausus se credere caelo",
	16 :"insuetum per iter gelidas enauit ad Arctos,",
	17 :"Chalcidicaque leuis tandem super astitit arce.",
	18 :"redditus his primum terris tibi, Phoebe, sacrauit",
	19 :"remigium alarum posuitque immania templa.",
	20 :"in foribus letum Androgeo; tum pendere poenas",
	21 :"Cecropidae iussi (miserum!) septena quotannis",
	22 :"corpora natorum; stat ductis sortibus urna.",
	23 :"contra elata mari respondet Cnosia tellus:",
	24 :"hic crudelis amor tauri suppostaque furto",
	25 :"Pasiphae mixtumque genus prolesque biformis",
	26 :"Minotaurus inest, Veneris monimenta nefandae,",
	27 :"hic labor ille domus et inextricabilis error;",
	28 :"magnum reginae sed enim miseratus amorem",
	29 :"Daedalus ipse dolos tecti ambagesque resoluit,",
	30 :"caeca regens filo uestigia. tu quoque magnam",
	31 :"partem opere in tanto, sineret dolor, Icare, haberes.",
	32 :"bis conatus erat casus effingere in auro,",
	33 :"bis patriae cecidere manus. quin protinus omnia",
	34 :"perlegerent oculis, ni iam praemissus Achates",
	35 :"adforet atque una Phoebi Triuiaeque sacerdos,",
	36 :"Deiphobe Glauci, fatur quae talia regi:",
	37 :"'non hoc ista sibi tempus spectacula poscit;",
	38 :"nunc grege de intacto septem mactare iuuencos",
	39 :"praestiterit, totidem lectas ex more bidentis.'",
	40 :"talibus adfata Aenean (nec sacra morantur",
	41 :"iussa uiri) Teucros uocat alta in templa sacerdos.",
	42 :"Excisum Euboicae latus ingens rupis in antrum,",
	43 :"quo lati ducunt aditus centum, ostia centum,",
	44 :"unde ruunt totidem uoces, responsa Sibyllae.",
	45 :"uentum erat ad limen, cum uirgo 'poscere fata",
	46 :"tempus' ait; 'deus ecce deus!' cui talia fanti",
	47 :"ante fores subito non uultus, non color unus,",
	48 :"non comptae mansere comae; sed pectus anhelum,",
	49 :"et rabie fera corda tument, maiorque uideri",
	50 :"nec mortale sonans, adflata est numine quando",
	51 :"iam propiore dei. 'cessas in uota precesque,",
	52 :"Tros' ait 'Aenea? cessas? neque enim ante dehiscent",
	53 :"attonitae magna ora domus.' et talia fata",
	54 :"conticuit. gelidus Teucris per dura cucurrit",
	55 :"ossa tremor, funditque preces rex pectore ab imo:",
	56 :"'Phoebe, grauis Troiae semper miserate labores,",
	57 :"Dardana qui Paridis derexti tela manusque",
	58 :"corpus in Aeacidae, magnas obeuntia terras",
	59 :"tot maria intraui duce te penitusque repostas",
	60 :"Massylum gentis praetentaque Syrtibus arua:",
	61 :"iam tandem Italiae fugientis prendimus oras.",
	62 :"hac Troiana tenus fuerit fortuna secuta;",
	63 :"uos quoque Pergameae iam fas est parcere genti,",
	64 :"dique deaeque omnes, quibus obstitit Ilium et ingens",
	65 :"gloria Dardaniae. tuque, o sanctissima uates,",
	66 :"praescia uenturi, da (non indebita posco",
	67 :"regna meis fatis) Latio considere Teucros",
	68 :"errantisque deos agitataque numina Troiae.",
	69 :"tum Phoebo et Triuiae solido de marmore templum",
	70 :"instituam festosque dies de nomine Phoebi.",
	71 :"te quoque magna manent regnis penetralia nostris:",
	72 :"hic ego namque tuas sortis arcanaque fata",
	73 :"dicta meae genti ponam, lectosque sacrabo,",
	74 :"alma, uiros. foliis tantum ne carmina manda,",
	75 :"ne turbata uolent rapidis ludibria uentis;",
	76 :"ipsa canas oro.' finem dedit ore loquendi.",
	77 :"At Phoebi nondum patiens immanis in antro",
	78 :"bacchatur uates, magnum si pectore possit",
	79 :"excussisse deum; tanto magis ille fatigat",
	80 :"os rabidum, fera corda domans, fingitque premendo.",
	81 :"ostia iamque domus patuere ingentia centum",
	82 :"sponte sua uatisque ferunt responsa per auras:",
	83 :"'o tandem magnis pelagi defuncte periclis",
	84 :"(sed terrae grauiora manent), in regna Lauini",
	85 :"Dardanidae uenient (mitte hanc de pectore curam),",
	86 :"sed non et uenisse uolent. bella, horrida bella,",
	87 :"et Thybrim multo spumantem sanguine cerno.",
	88 :"non Simois tibi nec Xanthus nec Dorica castra",
	89 :"defuerint; alius Latio iam partus Achilles,",
	90 :"natus et ipse dea; nec Teucris addita Iuno",
	91 :"usquam aberit, cum tu supplex in rebus egenis",
	92 :"quas gentis Italum aut quas non oraueris urbes!",
	93 :"causa mali tanti coniunx iterum hospita Teucris",
	94 :"externique iterum thalami.",
	95 :"tu ne cede malis, sed contra audentior ito,",
	96 :"qua tua te Fortuna sinet. uia prima salutis",
	97 :"(quod minime reris) Graia pandetur ab urbe.'",
	98 :"Talibus ex adyto dictis Cumaea Sibylla",
	99 :"horrendas canit ambages antroque remugit,",
	100 :"obscuris uera inuoluens: ea frena furenti",
	101 :"concutit et stimulos sub pectore uertit Apollo.",
	102 :"ut primum cessit furor et rabida ora quierunt,",
	103 :"incipit Aeneas heros: 'non ulla laborum,",
	104 :"o uirgo, noua mi facies inopinaue surgit;",
	105 :"omnia praecepi atque animo mecum ante peregi.",
	106 :"unum oro: quando hic inferni ianua regis",
	107 :"dicitur et tenebrosa palus Acheronte refuso,",
	108 :"ire ad conspectum cari genitoris et ora",
	109 :"contingat; doceas iter et sacra ostia pandas.",
	110 :"illum ego per flammas et mille sequentia tela",
	111 :"eripui his umeris medioque ex hoste recepi;",
	112 :"ille meum comitatus iter maria omnia mecum",
	113 :"atque omnis pelagique minas caelique ferebat,",
	114 :"inualidus, uiris ultra sortemque senectae.",
	115 :"quin, ut te supplex peterem et tua limina adirem,",
	116 :"idem orans mandata dabat. gnatique patrisque,",
	117 :"alma, precor, miserere (potes namque omnia, nec te",
	118 :"nequiquam lucis Hecate praefecit Auernis),",
	119 :"si potuit manis accersere coniugis Orpheus",
	120 :"Threicia fretus cithara fidibusque canoris,",
	121 :"si fratrem Pollux alterna morte redemit",
	122 :"itque reditque uiam totiens. quid Thesea, magnum",
	123 :"quid memorem Alciden? et mi genus ab Ioue summo.'",
	124 :"Talibus orabat dictis arasque tenebat,",
	125 :"cum sic orsa loqui uates: 'sate sanguine diuum,",
	126 :"Tros Anchisiade, facilis descensus Auerno:",
	127 :"noctes atque dies patet atri ianua Ditis;",
	128 :"sed reuocare gradum superasque euadere ad auras,",
	129 :"hoc opus, hic labor est. pauci, quos aequus amauit",
	130 :"Iuppiter aut ardens euexit ad aethera uirtus,",
	131 :"dis geniti potuere. tenent media omnia siluae,",
	132 :"Cocytusque sinu labens circumuenit atro.",
	133 :"quod si tantus amor menti, si tanta cupido est",
	134 :"bis Stygios innare lacus, bis nigra uidere",
	135 :"Tartara, et insano iuuat indulgere labori,",
	136 :"accipe quae peragenda prius. latet arbore opaca",
	137 :"aureus et foliis et lento uimine ramus,",
	138 :"Iunoni infernae dictus sacer; hunc tegit omnis",
	139 :"lucus et obscuris claudunt conuallibus umbrae.",
	140 :"sed non ante datur telluris operta subire",
	141 :"auricomos quam quis decerpserit arbore fetus.",
	142 :"hoc sibi pulchra suum ferri Proserpina munus",
	143 :"instituit. primo auulso non deficit alter",
	144 :"aureus, et simili frondescit uirga metallo.",
	145 :"ergo alte uestiga oculis et rite repertum",
	146 :"carpe manu; namque ipse uolens facilisque sequetur,",
	147 :"si te fata uocant; aliter non uiribus ullis",
	148 :"uincere nec duro poteris conuellere ferro.",
	149 :"praeterea iacet exanimum tibi corpus amici",
	150 :"(heu nescis) totamque incestat funere classem,",
	151 :"dum consulta petis nostroque in limine pendes.",
	152 :"sedibus hunc refer ante suis et conde sepulcro.",
	153 :"duc nigras pecudes; ea prima piacula sunto.",
	154 :"sic demum lucos Stygis et regna inuia uiuis",
	155 :"aspicies.' dixit, pressoque obmutuit ore.",
	156 :"Aeneas maesto defixus lumina uultu",
	157 :"ingreditur linquens antrum, caecosque uolutat",
	158 :"euentus animo secum. cui fidus Achates",
	159 :"it comes et paribus curis uestigia figit.",
	160 :"multa inter sese uario sermone serebant,",
	161 :"quem socium exanimum uates, quod corpus humandum",
	162 :"diceret. atque illi Misenum in litore sicco,",
	163 :"ut uenere, uident indigna morte peremptum,",
	164 :"Misenum Aeoliden, quo non praestantior alter",
	165 :"aere ciere uiros Martemque accendere cantu.",
	166 :"Hectoris hic magni fuerat comes, Hectora circum",
	167 :"et lituo pugnas insignis obibat et hasta.",
	168 :"postquam illum uita uictor spoliauit Achilles,",
	169 :"Dardanio Aeneae sese fortissimus heros",
	170 :"addiderat socium, non inferiora secutus.",
	171 :"sed tum, forte caua dum personat aequora concha,",
	172 :"demens, et cantu uocat in certamina diuos,",
	173 :"aemulus exceptum Triton, si credere dignum est,",
	174 :"inter saxa uirum spumosa immerserat unda.",
	175 :"ergo omnes magno circum clamore fremebant,",
	176 :"praecipue pius Aeneas. tum iussa Sibyllae,",
	177 :"haud mora, festinant flentes aramque sepulcri",
	178 :"congerere arboribus caeloque educere certant.",
	179 :"itur in antiquam siluam, stabula alta ferarum;",
	180 :"procumbunt piceae, sonat icta securibus ilex",
	181 :"fraxineaeque trabes cuneis et fissile robur",
	182 :"scinditur, aduoluunt ingentis montibus ornos.",
	183 :"Nec non Aeneas opera inter talia primus",
	184 :"hortatur socios paribusque accingitur armis.",
	185 :"atque haec ipse suo tristi cum corde uolutat",
	186 :"aspectans siluam immensam, et sic forte precatur:",
	187 :"'si nunc se nobis ille aureus arbore ramus",
	188 :"ostendat nemore in tanto! quando omnia uere",
	189 :"heu nimium de te uates, Misene, locuta est.'",
	190 :"uix ea fatus erat, geminae cum forte columbae",
	191 :"ipsa sub ora uiri caelo uenere uolantes,",
	192 :"et uiridi sedere solo. tum maximus heros",
	193 :"maternas agnouit auis laetusque precatur:",
	194 :"'este duces, o, si qua uia est, cursumque per auras",
	195 :"derigite in lucos ubi pinguem diues opacat",
	196 :"ramus humum. tuque, o, dubiis ne defice rebus,",
	197 :"diua parens.' sic effatus uestigia pressit",
	198 :"obseruans quae signa ferant, quo tendere pergant.",
	199 :"pascentes illae tantum prodire uolando",
	200 :"quantum acie possent oculi seruare sequentum.",
	201 :"inde ubi uenere ad fauces graue olentis Auerni,",
	202 :"tollunt se celeres liquidumque per aera lapsae",
	203 :"sedibus optatis gemina super arbore sidunt,",
	204 :"discolor unde auri per ramos aura refulsit.",
	205 :"quale solet siluis brumali frigore uiscum",
	206 :"fronde uirere noua, quod non sua seminat arbos,",
	207 :"et croceo fetu teretis circumdare truncos,",
	208 :"talis erat species auri frondentis opaca",
	209 :"ilice, sic leni crepitabat brattea uento.",
	210 :"corripit Aeneas extemplo auidusque refringit",
	211 :"cunctantem, et uatis portat sub tecta Sibyllae.",
	212 :"Nec minus interea Misenum in litore Teucri",
	213 :"flebant et cineri ingrato suprema ferebant.",
	214 :"principio pinguem taedis et robore secto",
	215 :"ingentem struxere pyram, cui frondibus atris",
	216 :"intexunt latera et feralis ante cupressos",
	217 :"constituunt, decorantque super fulgentibus armis.",
	218 :"pars calidos latices et aena undantia flammis",
	219 :"expediunt, corpusque lauant frigentis et unguunt.",
	220 :"fit gemitus. tum membra toro defleta reponunt",
	221 :"purpureasque super uestis, uelamina nota,",
	222 :"coniciunt. pars ingenti subiere feretro,",
	223 :"triste ministerium, et subiectam more parentum",
	224 :"auersi tenuere facem. congesta cremantur",
	225 :"turea dona, dapes, fuso crateres oliuo.",
	226 :"postquam conlapsi cineres et flamma quieuit,",
	227 :"reliquias uino et bibulam lauere fauillam,",
	228 :"ossaque lecta cado texit Corynaeus aeno.",
	229 :"idem ter socios pura circumtulit unda",
	230 :"spargens rore leui et ramo felicis oliuae,",
	231 :"lustrauitque uiros dixitque nouissima uerba.",
	232 :"at pius Aeneas ingenti mole sepulcrum",
	233 :"imponit suaque arma uiro remumque tubamque",
	234 :"monte sub aerio, qui nunc Misenus ab illo",
	235 :"dicitur aeternumque tenet per saecula nomen.",
	236 :"His actis propere exsequitur praecepta Sibyllae.",
	237 :"spelunca alta fuit uastoque immanis hiatu,",
	238 :"scrupea, tuta lacu nigro nemorumque tenebris,",
	239 :"quam super haud ullae poterant impune uolantes",
	240 :"tendere iter pennis: talis sese halitus atris",
	241 :"faucibus effundens supera ad conuexa ferebat.",
	242 :"[unde locum Grai dixerunt nomine Aornum.]",
	243 :"quattuor hic primum nigrantis terga iuuencos",
	244 :"constituit frontique inuergit uina sacerdos,",
	245 :"et summas carpens media inter cornua saetas",
	246 :"ignibus imponit sacris, libamina prima,",
	247 :"uoce uocans Hecaten caeloque Ereboque potentem.",
	248 :"supponunt alii cultros tepidumque cruorem",
	249 :"succipiunt pateris. ipse atri uelleris agnam",
	250 :"Aeneas matri Eumenidum magnaeque sorori",
	251 :"ense ferit, sterilemque tibi, Proserpina, uaccam;",
	252 :"tum Stygio regi nocturnas incohat aras",
	253 :"et solida imponit taurorum uiscera flammis,",
	254 :"pingue super oleum fundens ardentibus extis.",
	255 :"ecce autem primi sub limina solis et ortus",
	256 :"sub pedibus mugire solum et iuga coepta moueri",
	257 :"siluarum, uisaeque canes ululare per umbram",
	258 :"aduentante dea. 'procul, o procul este, profani,'",
	259 :"conclamat uates, 'totoque absistite luco;",
	260 :"tuque inuade uiam uaginaque eripe ferrum:",
	261 :"nunc animis opus, Aenea, nunc pectore firmo.'",
	262 :"tantum effata furens antro se immisit aperto;",
	263 :"ille ducem haud timidis uadentem passibus aequat.",
	264 :"Di, quibus imperium est animarum, umbraeque silentes",
	265 :"et Chaos et Phlegethon, loca nocte tacentia late,",
	266 :"sit mihi fas audita loqui, sit numine uestro",
	267 :"pandere res alta terra et caligine mersas.",
	268 :"Ibant obscuri sola sub nocte per umbram",
	269 :"perque domos Ditis uacuas et inania regna:",
	270 :"quale per incertam lunam sub luce maligna",
	271 :"est iter in siluis, ubi caelum condidit umbra",
	272 :"Iuppiter, et rebus nox abstulit atra colorem.",
	273 :"uestibulum ante ipsum primisque in faucibus Orci",
	274 :"Luctus et ultrices posuere cubilia Curae,",
	275 :"pallentesque habitant Morbi tristisque Senectus,",
	276 :"et Metus et malesuada Fames ac turpis Egestas,",
	277 :"terribiles uisu formae, Letumque Labosque;",
	278 :"tum consanguineus Leti Sopor et mala mentis",
	279 :"Gaudia, mortiferumque aduerso in limine Bellum,",
	280 :"ferreique Eumenidum thalami et Discordia demens",
	281 :"uipereum crinem uittis innexa cruentis.",
	282 :"in medio ramos annosaque bracchia pandit",
	283 :"ulmus opaca, ingens, quam sedem Somnia uulgo",
	284 :"uana tenere ferunt, foliisque sub omnibus haerent.",
	285 :"multaque praeterea uariarum monstra ferarum,",
	286 :"Centauri in foribus stabulant Scyllaeque biformes",
	287 :"et centumgeminus Briareus ac belua Lernae",
	288 :"horrendum stridens, flammisque armata Chimaera,",
	289 :"Gorgones Harpyiaeque et forma tricorporis umbrae.",
	290 :"corripit hic subita trepidus formidine ferrum",
	291 :"Aeneas strictamque aciem uenientibus offert,",
	292 :"et ni docta comes tenuis sine corpore uitas",
	293 :"admoneat uolitare caua sub imagine formae,",
	294 :"inruat et frustra ferro diuerberet umbras.",
	295 :"Hinc uia Tartarei quae fert Acherontis ad undas.",
	296 :"turbidus hic caeno uastaque uoragine gurges",
	297 :"aestuat atque omnem Cocyto eructat harenam.",
	298 :"portitor has horrendus aquas et flumina seruat",
	299 :"terribili squalore Charon, cui plurima mento",
	300 :"canities inculta iacet, stant lumina flamma,",
	301 :"sordidus ex umeris nodo dependet amictus.",
	302 :"ipse ratem conto subigit uelisque ministrat",
	303 :"et ferruginea subuectat corpora cumba,",
	304 :"iam senior, sed cruda deo uiridisque senectus.",
	305 :"huc omnis turba ad ripas effusa ruebat,",
	306 :"matres atque uiri defunctaque corpora uita",
	307 :"magnanimum heroum, pueri innuptaeque puellae,",
	308 :"impositique rogis iuuenes ante ora parentum:",
	309 :"quam multa in siluis autumni frigore primo",
	310 :"lapsa cadunt folia, aut ad terram gurgite ab alto",
	311 :"quam multae glomerantur aues, ubi frigidus annus",
	312 :"trans pontum fugat et terris immittit apricis.",
	313 :"stabant orantes primi transmittere cursum",
	314 :"tendebantque manus ripae ulterioris amore.",
	315 :"nauita sed tristis nunc hos nunc accipit illos,",
	316 :"ast alios longe summotos arcet harena.",
	317 :"Aeneas miratus enim motusque tumultu",
	318 :"'dic,' ait, 'o uirgo, quid uult concursus ad amnem?",
	319 :"quidue petunt animae? uel quo discrimine ripas",
	320 :"hae linquunt, illae remis uada liuida uerrunt?'",
	321 :"olli sic breuiter fata est longaeua sacerdos:",
	322 :"'Anchisa generate, deum certissima proles,",
	323 :"Cocyti stagna alta uides Stygiamque paludem,",
	324 :"di cuius iurare timent et fallere numen.",
	325 :"haec omnis, quam cernis, inops inhumataque turba est;",
	326 :"portitor ille Charon; hi, quos uehit unda, sepulti.",
	327 :"nec ripas datur horrendas et rauca fluenta",
	328 :"transportare prius quam sedibus ossa quierunt.",
	329 :"centum errant annos uolitantque haec litora circum;",
	330 :"tum demum admissi stagna exoptata reuisunt.'",
	331 :"constitit Anchisa satus et uestigia pressit",
	332 :"multa putans sortemque animo miseratus iniquam.",
	333 :"cernit ibi maestos et mortis honore carentis",
	334 :"Leucaspim et Lyciae ductorem classis Oronten,",
	335 :"quos simul a Troia uentosa per aequora uectos",
	336 :"obruit Auster, aqua inuoluens nauemque uirosque.",
	337 :"Ecce gubernator sese Palinurus agebat,",
	338 :"qui Libyco nuper cursu, dum sidera seruat,",
	339 :"exciderat puppi mediis effusus in undis.",
	340 :"hunc ubi uix multa maestum cognouit in umbra,",
	341 :"sic prior adloquitur: 'quis te, Palinure, deorum",
	342 :"eripuit nobis medioque sub aequore mersit?",
	343 :"dic age. namque mihi, fallax haud ante repertus,",
	344 :"hoc uno responso animum delusit Apollo,",
	345 :"qui fore te ponto incolumem finisque canebat",
	346 :"uenturum Ausonios. en haec promissa fides est?'",
	347 :"ille autem: 'neque te Phoebi cortina fefellit,",
	348 :"dux Anchisiade, nec me deus aequore mersit.",
	349 :"namque gubernaclum multa ui forte reuulsum,",
	350 :"cui datus haerebam custos cursusque regebam,",
	351 :"praecipitans traxi mecum. maria aspera iuro",
	352 :"non ullum pro me tantum cepisse timorem,",
	353 :"quam tua ne spoliata armis, excussa magistro,",
	354 :"deficeret tantis nauis surgentibus undis.",
	355 :"tris Notus hibernas immensa per aequora noctes",
	356 :"uexit me uiolentus aqua; uix lumine quarto",
	357 :"prospexi Italiam summa sublimis ab unda.",
	358 :"paulatim adnabam terrae; iam tuta tenebam,",
	359 :"ni gens crudelis madida cum ueste grauatum",
	360 :"prensantemque uncis manibus capita aspera montis",
	361 :"ferro inuasisset praedamque ignara putasset.",
	362 :"nunc me fluctus habet uersantque in litore uenti.",
	363 :"quod te per caeli iucundum lumen et auras,",
	364 :"per genitorem oro, per spes surgentis Iuli,",
	365 :"eripe me his, inuicte, malis: aut tu mihi terram",
	366 :"inice, namque potes, portusque require Velinos;",
	367 :"aut tu, si qua uia est, si quam tibi diua creatrix",
	368 :"ostendit (neque enim, credo, sine numine diuum",
	369 :"flumina tanta paras Stygiamque innare paludem),",
	370 :"da dextram misero et tecum me tolle per undas,",
	371 :"sedibus ut saltem placidis in morte quiescam.'",
	372 :"talia fatus erat coepit cum talia uates:",
	373 :"'unde haec, o Palinure, tibi tam dira cupido?",
	374 :"tu Stygias inhumatus aquas amnemque seuerum",
	375 :"Eumenidum aspicies, ripamue iniussus adibis?",
	376 :"desine fata deum flecti sperare precando,",
	377 :"sed cape dicta memor, duri solacia casus.",
	378 :"nam tua finitimi, longe lateque per urbes",
	379 :"prodigiis acti caelestibus, ossa piabunt",
	380 :"et statuent tumulum et tumulo sollemnia mittent,",
	381 :"aeternumque locus Palinuri nomen habebit.'",
	382 :"his dictis curae emotae pulsusque parumper",
	383 :"corde dolor tristi; gaudet cognomine terra.",
	384 :"Ergo iter inceptum peragunt fluuioque propinquant.",
	385 :"nauita quos iam inde ut Stygia prospexit ab unda",
	386 :"per tacitum nemus ire pedemque aduertere ripae,",
	387 :"sic prior adgreditur dictis atque increpat ultro:",
	388 :"'quisquis es, armatus qui nostra ad flumina tendis,",
	389 :"fare age, quid uenias, iam istinc et comprime gressum.",
	390 :"umbrarum hic locus est, somni noctisque soporae:",
	391 :"corpora uiua nefas Stygia uectare carina.",
	392 :"nec uero Alciden me sum laetatus euntem",
	393 :"accepisse lacu, nec Thesea Pirithoumque,",
	394 :"dis quamquam geniti atque inuicti uiribus essent.",
	395 :"Tartareum ille manu custodem in uincla petiuit",
	396 :"ipsius a solio regis traxitque trementem;",
	397 :"hi dominam Ditis thalamo deducere adorti.'",
	398 :"quae contra breuiter fata est Amphrysia uates:",
	399 :"'nullae hic insidiae tales (absiste moueri),",
	400 :"nec uim tela ferunt; licet ingens ianitor antro",
	401 :"aeternum latrans exsanguis terreat umbras,",
	402 :"casta licet patrui seruet Proserpina limen.",
	403 :"Troius Aeneas, pietate insignis et armis,",
	404 :"ad genitorem imas Erebi descendit ad umbras.",
	405 :"si te nulla mouet tantae pietatis imago,",
	406 :"at ramum hunc' (aperit ramum qui ueste latebat)",
	407 :"'agnoscas.' tumida ex ira tum corda residunt;",
	408 :"nec plura his. ille admirans uenerabile donum",
	409 :"fatalis uirgae longo post tempore uisum",
	410 :"caeruleam aduertit puppim ripaeque propinquat.",
	411 :"inde alias animas, quae per iuga longa sedebant,",
	412 :"deturbat laxatque foros; simul accipit alueo",
	413 :"ingentem Aenean. gemuit sub pondere cumba",
	414 :"sutilis et multam accepit rimosa paludem.",
	415 :"tandem trans fluuium incolumis uatemque uirumque",
	416 :"informi limo glaucaque exponit in ulua.",
	417 :"Cerberus haec ingens latratu regna trifauci",
	418 :"personat aduerso recubans immanis in antro.",
	419 :"cui uates horrere uidens iam colla colubris",
	420 :"melle soporatam et medicatis frugibus offam",
	421 :"obicit. ille fame rabida tria guttura pandens",
	422 :"corripit obiectam, atque immania terga resoluit",
	423 :"fusus humi totoque ingens extenditur antro.",
	424 :"occupat Aeneas aditum custode sepulto",
	425 :"euaditque celer ripam inremeabilis undae.",
	426 :"Continuo auditae uoces uagitus et ingens",
	427 :"infantumque animae flentes, in limine primo",
	428 :"quos dulcis uitae exsortis et ab ubere raptos",
	429 :"abstulit atra dies et funere mersit acerbo;",
	430 :"hos iuxta falso damnati crimine mortis.",
	431 :"nec uero hae sine sorte datae, sine iudice, sedes:",
	432 :"quaesitor Minos urnam mouet; ille silentum",
	433 :"consiliumque uocat uitasque et crimina discit.",
	434 :"proxima deinde tenent maesti loca, qui sibi letum",
	435 :"insontes peperere manu lucemque perosi",
	436 :"proiecere animas. quam uellent aethere in alto",
	437 :"nunc et pauperiem et duros perferre labores!",
	438 :"fas obstat, tristisque palus inamabilis undae",
	439 :"alligat et nouies Styx interfusa coercet.",
	440 :"nec procul hinc partem fusi monstrantur in omnem",
	441 :"Lugentes campi; sic illos nomine dicunt.",
	442 :"hic quos durus amor crudeli tabe peredit",
	443 :"secreti celant calles et myrtea circum",
	444 :"silua tegit; curae non ipsa in morte relinquunt.",
	445 :"his Phaedram Procrinque locis maestamque Eriphylen",
	446 :"crudelis nati monstrantem uulnera cernit,",
	447 :"Euadnenque et Pasiphaen; his Laodamia",
	448 :"it comes et iuuenis quondam, nunc femina, Caeneus",
	449 :"rursus et in ueterem fato reuoluta figuram.",
	450 :"inter quas Phoenissa recens a uulnere Dido",
	451 :"errabat silua in magna; quam Troius heros",
	452 :"ut primum iuxta stetit agnouitque per umbras",
	453 :"obscuram, qualem primo qui surgere mense",
	454 :"aut uidet aut uidisse putat per nubila lunam,",
	455 :"demisit lacrimas dulcique adfatus amore est:",
	456 :"'infelix Dido, uerus mihi nuntius ergo",
	457 :"uenerat exstinctam ferroque extrema secutam?",
	458 :"funeris heu tibi causa fui? per sidera iuro,",
	459 :"per superos et si qua fides tellure sub ima est,",
	460 :"inuitus, regina, tuo de litore cessi.",
	461 :"sed me iussa deum, quae nunc has ire per umbras,",
	462 :"per loca senta situ cogunt noctemque profundam,",
	463 :"imperiis egere suis; nec credere quiui",
	464 :"hunc tantum tibi me discessu ferre dolorem.",
	465 :"siste gradum teque aspectu ne subtrahe nostro.",
	466 :"quem fugis? extremum fato quod te adloquor hoc est.'",
	467 :"talibus Aeneas ardentem et torua tuentem",
	468 :"lenibat dictis animum lacrimasque ciebat.",
	469 :"illa solo fixos oculos auersa tenebat",
	470 :"nec magis incepto uultum sermone mouetur",
	471 :"quam si dura silex aut stet Marpesia cautes.",
	472 :"tandem corripuit sese atque inimica refugit",
	473 :"in nemus umbriferum, coniunx ubi pristinus illi",
	474 :"respondet curis aequatque Sychaeus amorem.",
	475 :"nec minus Aeneas casu percussus iniquo",
	476 :"prosequitur lacrimis longe et miseratur euntem.",
	477 :"Inde datum molitur iter. iamque arua tenebant",
	478 :"ultima, quae bello clari secreta frequentant.",
	479 :"hic illi occurrit Tydeus, hic inclutus armis",
	480 :"Parthenopaeus et Adrasti pallentis imago,",
	481 :"hic multum fleti ad superos belloque caduci",
	482 :"Dardanidae, quos ille omnis longo ordine cernens",
	483 :"ingemuit, Glaucumque Medontaque Thersilochumque,",
	484 :"tris Antenoridas Cererique sacrum Polyboeten,",
	485 :"Idaeumque etiam currus, etiam arma tenentem.",
	486 :"circumstant animae dextra laeuaque frequentes,",
	487 :"nec uidisse semel satis est; iuuat usque morari",
	488 :"et conferre gradum et ueniendi discere causas.",
	489 :"at Danaum proceres Agamemnoniaeque phalanges",
	490 :"ut uidere uirum fulgentiaque arma per umbras,",
	491 :"ingenti trepidare metu; pars uertere terga,",
	492 :"ceu quondam petiere rates, pars tollere uocem",
	493 :"exiguam: inceptus clamor frustratur hiantis.",
	494 :"Atque hic Priamiden laniatum corpore toto",
	495 :"Deiphobum uidet et lacerum crudeliter ora,",
	496 :"ora manusque ambas, populataque tempora raptis",
	497 :"auribus et truncas inhonesto uulnere naris.",
	498 :"uix adeo agnouit pauitantem ac dira tegentem",
	499 :"supplicia, et notis compellat uocibus ultro:",
	500 :"'Deiphobe armipotens, genus alto a sanguine Teucri,",
	501 :"quis tam crudelis optauit sumere poenas?",
	502 :"cui tantum de te licuit? mihi fama suprema",
	503 :"nocte tulit fessum uasta te caede Pelasgum",
	504 :"procubuisse super confusae stragis aceruum.",
	505 :"tunc egomet tumulum Rhoeteo in litore inanem",
	506 :"constitui et magna manis ter uoce uocaui.",
	507 :"nomen et arma locum seruant; te, amice, nequiui",
	508 :"conspicere et patria decedens ponere terra.'",
	509 :"ad quae Priamides: 'nihil o tibi, amice, relictum;",
	510 :"omnia Deiphobo soluisti et funeris umbris.",
	511 :"sed me fata mea et scelus exitiale Lacaenae",
	512 :"his mersere malis; illa haec monimenta reliquit.",
	513 :"namque ut supremam falsa inter gaudia noctem",
	514 :"egerimus, nosti: et nimium meminisse necesse est.",
	515 :"cum fatalis equus saltu super ardua uenit",
	516 :"Pergama et armatum peditem grauis attulit aluo,",
	517 :"illa chorum simulans euhantis orgia circum",
	518 :"ducebat Phrygias; flammam media ipsa tenebat",
	519 :"ingentem et summa Danaos ex arce uocabat.",
	520 :"tum me confectum curis somnoque grauatum",
	521 :"infelix habuit thalamus, pressitque iacentem",
	522 :"dulcis et alta quies placidaeque simillima morti.",
	523 :"egregia interea coniunx arma omnia tectis",
	524 :"emouet, et fidum capiti subduxerat ensem:",
	525 :"intra tecta uocat Menelaum et limina pandit,",
	526 :"scilicet id magnum sperans fore munus amanti,",
	527 :"et famam exstingui ueterum sic posse malorum.",
	528 :"quid moror? inrumpunt thalamo, comes additus una",
	529 :"hortator scelerum Aeolides. di, talia Grais",
	530 :"instaurate, pio si poenas ore reposco.",
	531 :"sed te qui uiuum casus, age fare uicissim,",
	532 :"attulerint. pelagine uenis erroribus actus",
	533 :"an monitu diuum? an quae te fortuna fatigat,",
	534 :"ut tristis sine sole domos, loca turbida, adires?'",
	535 :"Hac uice sermonum roseis Aurora quadrigis",
	536 :"iam medium aetherio cursu traiecerat axem;",
	537 :"et fors omne datum traherent per talia tempus,",
	538 :"sed comes admonuit breuiterque adfata Sibylla est:",
	539 :"'nox ruit, Aenea; nos flendo ducimus horas.",
	540 :"hic locus est, partis ubi se uia findit in ambas:",
	541 :"dextera quae Ditis magni sub moenia tendit,",
	542 :"hac iter Elysium nobis; at laeua malorum",
	543 :"exercet poenas et ad impia Tartara mittit.'",
	544 :"Deiphobus contra: 'ne saeui, magna sacerdos;",
	545 :"discedam, explebo numerum reddarque tenebris.",
	546 :"i decus, i, nostrum; melioribus utere fatis.'",
	547 :"tantum effatus, et in uerbo uestigia torsit.",
	548 :"Respicit Aeneas subito et sub rupe sinistra",
	549 :"moenia lata uidet triplici circumdata muro,",
	550 :"quae rapidus flammis ambit torrentibus amnis,",
	551 :"Tartareus Phlegethon, torquetque sonantia saxa.",
	552 :"porta aduersa ingens solidoque adamante columnae,",
	553 :"uis ut nulla uirum, non ipsi exscindere bello",
	554 :"caelicolae ualeant; stat ferrea turris ad auras,",
	555 :"Tisiphoneque sedens palla succincta cruenta",
	556 :"uestibulum exsomnis seruat noctesque diesque.",
	557 :"hinc exaudiri gemitus et saeua sonare",
	558 :"uerbera, tum stridor ferri tractaeque catenae.",
	559 :"constitit Aeneas strepitumque exterritus hausit.",
	560 :"'quae scelerum facies? o uirgo, effare; quibusue",
	561 :"urgentur poenis? quis tantus plangor ad auras?'",
	562 :"tum uates sic orsa loqui: 'dux inclute Teucrum,",
	563 :"nulli fas casto sceleratum insistere limen;",
	564 :"sed me cum lucis Hecate praefecit Auernis,",
	565 :"ipsa deum poenas docuit perque omnia duxit.",
	566 :"Cnosius haec Rhadamanthus habet durissima regna",
	567 :"castigatque auditque dolos subigitque fateri",
	568 :"quae quis apud superos furto laetatus inani",
	569 :"distulit in seram commissa piacula mortem.",
	570 :"continuo sontis ultrix accincta flagello",
	571 :"Tisiphone quatit insultans, toruosque sinistra",
	572 :"intentans anguis uocat agmina saeua sororum.",
	573 :"tum demum horrisono stridentes cardine sacrae",
	574 :"panduntur portae. cernis custodia qualis",
	575 :"uestibulo sedeat, facies quae limina seruet?",
	576 :"quinquaginta atris immanis hiatibus Hydra",
	577 :"saeuior intus habet sedem. tum Tartarus ipse",
	578 :"bis patet in praeceps tantum tenditque sub umbras",
	579 :"quantus ad aetherium caeli suspectus Olympum.",
	580 :"hic genus antiquum Terrae, Titania pubes,",
	581 :"fulmine deiecti fundo uoluuntur in imo.",
	582 :"hic et Aloidas geminos immania uidi",
	583 :"corpora, qui manibus magnum rescindere caelum",
	584 :"adgressi superisque Iouem detrudere regnis.",
	585 :"uidi et crudelis dantem Salmonea poenas,",
	586 :"dum flammas Iouis et sonitus imitatur Olympi.",
	587 :"quattuor hic inuectus equis et lampada quassans",
	588 :"per Graium populos mediaeque per Elidis urbem",
	589 :"ibat ouans, diuumque sibi poscebat honorem,",
	590 :"demens, qui nimbos et non imitabile fulmen",
	591 :"aere et cornipedum pulsu simularet equorum.",
	592 :"at pater omnipotens densa inter nubila telum",
	593 :"contorsit, non ille faces nec fumea taedis",
	594 :"lumina, praecipitemque immani turbine adegit.",
	595 :"nec non et Tityon, Terrae omniparentis alumnum,",
	596 :"cernere erat, per tota nouem cui iugera corpus",
	597 :"porrigitur, rostroque immanis uultur obunco",
	598 :"immortale iecur tondens fecundaque poenis",
	599 :"uiscera rimaturque epulis habitatque sub alto",
	600 :"pectore, nec fibris requies datur ulla renatis.",
	601 :"quid memorem Lapithas, Ixiona Pirithoumque?",
	602 :"quos super atra silex iam iam lapsura cadentique",
	603 :"imminet adsimilis; lucent genialibus altis",
	604 :"aurea fulcra toris, epulaeque ante ora paratae",
	605 :"regifico luxu; Furiarum maxima iuxta",
	606 :"accubat et manibus prohibet contingere mensas,",
	607 :"exsurgitque facem attollens atque intonat ore.",
	608 :"hic, quibus inuisi fratres, dum uita manebat,",
	609 :"pulsatusue parens et fraus innexa clienti,",
	610 :"aut qui diuitiis soli incubuere repertis",
	611 :"nec partem posuere suis (quae maxima turba est),",
	612 :"quique ob adulterium caesi, quique arma secuti",
	613 :"impia nec ueriti dominorum fallere dextras,",
	614 :"inclusi poenam exspectant. ne quaere doceri",
	615 :"quam poenam, aut quae forma uiros fortunaue mersit.",
	616 :"saxum ingens uoluunt alii, radiisque rotarum",
	617 :"districti pendent; sedet aeternumque sedebit",
	618 :"infelix Theseus, Phlegyasque miserrimus omnis",
	619 :"admonet et magna testatur uoce per umbras:",
	620 :"\"discite iustitiam moniti et non temnere diuos.\"",
	621 :"uendidit hic auro patriam dominumque potentem",
	622 :"imposuit; fixit leges pretio atque refixit;",
	623 :"hic thalamum inuasit natae uetitosque hymenaeos:",
	624 :"ausi omnes immane nefas ausoque potiti.",
	625 :"non, mihi si linguae centum sint oraque centum,",
	626 :"ferrea uox, omnis scelerum comprendere formas,",
	627 :"omnia poenarum percurrere nomina possim.'",
	628 :"Haec ubi dicta dedit Phoebi longaeua sacerdos,",
	629 :"'sed iam age, carpe uiam et susceptum perfice munus;",
	630 :"acceleremus' ait; 'Cyclopum educta caminis",
	631 :"moenia conspicio atque aduerso fornice portas,",
	632 :"haec ubi nos praecepta iubent deponere dona.'",
	633 :"dixerat et pariter gressi per opaca uiarum",
	634 :"corripiunt spatium medium foribusque propinquant.",
	635 :"occupat Aeneas aditum corpusque recenti",
	636 :"spargit aqua ramumque aduerso in limine figit.",
	637 :"His demum exactis, perfecto munere diuae,",
	638 :"deuenere locos laetos et amoena uirecta",
	639 :"fortunatorum nemorum sedesque beatas.",
	640 :"largior hic campos aether et lumine uestit",
	641 :"purpureo, solemque suum, sua sidera norunt.",
	642 :"pars in gramineis exercent membra palaestris,",
	643 :"contendunt ludo et fulua luctantur harena;",
	644 :"pars pedibus plaudunt choreas et carmina dicunt.",
	645 :"nec non Threicius longa cum ueste sacerdos",
	646 :"obloquitur numeris septem discrimina uocum,",
	647 :"iamque eadem digitis, iam pectine pulsat eburno.",
	648 :"hic genus antiquum Teucri, pulcherrima proles,",
	649 :"magnanimi heroes nati melioribus annis,",
	650 :"Ilusque Assaracusque et Troiae Dardanus auctor.",
	651 :"arma procul currusque uirum miratur inanis;",
	652 :"stant terra defixae hastae passimque soluti",
	653 :"per campum pascuntur equi. quae gratia currum",
	654 :"armorumque fuit uiuis, quae cura nitentis",
	655 :"pascere equos, eadem sequitur tellure repostos.",
	656 :"conspicit, ecce, alios dextra laeuaque per herbam",
	657 :"uescentis laetumque choro paeana canentis",
	658 :"inter odoratum lauris nemus, unde superne",
	659 :"plurimus Eridani per siluam uoluitur amnis.",
	660 :"hic manus ob patriam pugnando uulnera passi,",
	661 :"quique sacerdotes casti, dum uita manebat,",
	662 :"quique pii uates et Phoebo digna locuti,",
	663 :"inuentas aut qui uitam excoluere per artis",
	664 :"quique sui memores aliquos fecere merendo:",
	665 :"omnibus his niuea cinguntur tempora uitta.",
	666 :"quos circumfusos sic est adfata Sibylla,",
	667 :"Musaeum ante omnis (medium nam plurima turba",
	668 :"hunc habet atque umeris exstantem suspicit altis):",
	669 :"'dicite, felices animae tuque optime uates,",
	670 :"quae regio Anchisen, quis habet locus? illius ergo",
	671 :"uenimus et magnos Erebi tranauimus amnis.'",
	672 :"atque huic responsum paucis ita reddidit heros:",
	673 :"'nulli certa domus; lucis habitamus opacis,",
	674 :"riparumque toros et prata recentia riuis",
	675 :"incolimus. sed uos, si fert ita corde uoluntas,",
	676 :"hoc superate iugum, et facili iam tramite sistam.'",
	677 :"dixit, et ante tulit gressum camposque nitentis",
	678 :"desuper ostentat; dehinc summa cacumina linquunt.",
	679 :"At pater Anchises penitus conualle uirenti",
	680 :"inclusas animas superumque ad lumen ituras",
	681 :"lustrabat studio recolens, omnemque suorum",
	682 :"forte recensebat numerum, carosque nepotes",
	683 :"fataque fortunasque uirum moresque manusque.",
	684 :"isque ubi tendentem aduersum per gramina uidit",
	685 :"Aenean, alacris palmas utrasque tetendit,",
	686 :"effusaeque genis lacrimae et uox excidit ore:",
	687 :"'uenisti tandem, tuaque exspectata parenti",
	688 :"uicit iter durum pietas? datur ora tueri,",
	689 :"nate, tua et notas audire et reddere uoces?",
	690 :"sic equidem ducebam animo rebarque futurum",
	691 :"tempora dinumerans, nec me mea cura fefellit.",
	692 :"quas ego te terras et quanta per aequora uectum",
	693 :"accipio! quantis iactatum, nate, periclis!",
	694 :"quam metui ne quid Libyae tibi regna nocerent!'",
	695 :"ille autem: 'tua me, genitor, tua tristis imago",
	696 :"saepius occurrens haec limina tendere adegit;",
	697 :"stant sale Tyrrheno classes. da iungere dextram,",
	698 :"da, genitor, teque amplexu ne subtrahe nostro.'",
	699 :"sic memorans largo fletu simul ora rigabat.",
	700 :"ter conatus ibi colo dare bracchia circum;",
	701 :"ter frustra comprensa manus effugit imago,",
	702 :"par leuibus uentis uolucrique simillima somno.",
	703 :"Interea uidet Aeneas in ualle reducta",
	704 :"seclusum nemus et uirgulta sonantia siluae,",
	705 :"Lethaeumque domos placidas qui praenatat amnem.",
	706 :"hunc circum innumerae gentes populique uolabant:",
	707 :"ac ueluti in pratis ubi apes aestate serena",
	708 :"floribus insidunt uariis et candida circum",
	709 :"lilia funduntur, strepit omnis murmure campus.",
	710 :"horrescit uisu subito causasque requirit",
	711 :"inscius Aeneas, quae sint ea flumina porro,",
	712 :"quiue uiri tanto complerint agmine ripas.",
	713 :"tum pater Anchises: 'animae, quibus altera fato",
	714 :"corpora debentur, Lethaei ad fluminis undam",
	715 :"securos latices et longa obliuia potant.",
	716 :"has equidem memorare tibi atque ostendere coram",
	717 :"iampridem, hanc prolem cupio enumerare meorum,",
	718 :"quo magis Italia mecum laetere reperta.'",
	719 :"'o pater, anne aliquas ad caelum hinc ire putandum est",
	720 :"sublimis animas iterumque ad tarda reuerti",
	721 :"corpora? quae lucis miseris tam dira cupido?'",
	722 :"'dicam equidem nec te suspensum, nate, tenebo'",
	723 :"suscipit Anchises atque ordine singula pandit.",
	724 :"'Principio caelum ac terras camposque liquentis",
	725 :"lucentemque globum lunae Titaniaque astra",
	726 :"spiritus intus alit, totamque infusa per artus",
	727 :"mens agitat molem et magno se corpore miscet.",
	728 :"inde hominum pecudumque genus uitaeque uolantum",
	729 :"et quae marmoreo fert monstra sub aequore pontus.",
	730 :"igneus est ollis uigor et caelestis origo",
	731 :"seminibus, quantum non noxia corpora tardant",
	732 :"terrenique hebetant artus moribundaque membra.",
	733 :"hinc metuunt cupiuntque, dolent gaudentque, neque auras",
	734 :"dispiciunt clausae tenebris et carcere caeco.",
	735 :"quin et supremo cum lumine uita reliquit,",
	736 :"non tamen omne malum miseris nec funditus omnes",
	737 :"corporeae excedunt pestes, penitusque necesse est",
	738 :"multa diu concreta modis inolescere miris.",
	739 :"ergo exercentur poenis ueterumque malorum",
	740 :"supplicia expendunt: aliae panduntur inanes",
	741 :"suspensae ad uentos, aliis sub gurgite uasto",
	742 :"infectum eluitur scelus aut exuritur igni:",
	743 :"quisque suos patimur manis. exinde per amplum",
	744 :"mittimur Elysium et pauci laeta arua tenemus,",
	745 :"donec longa dies perfecto temporis orbe",
	746 :"concretam exemit labem, purumque relinquit",
	747 :"aetherium sensum atque aurai simplicis ignem.",
	748 :"has omnis, ubi mille rotam uoluere per annos,",
	749 :"Lethaeum ad fluuium deus euocat agmine magno,",
	750 :"scilicet immemores supera ut conuexa reuisant",
	751 :"rursus, et incipiant in corpora uelle reuerti.'",
	752 :"Dixerat Anchises natumque unaque Sibyllam",
	753 :"conuentus trahit in medios turbamque sonantem,",
	754 :"et tumulum capit unde omnis longo ordine posset",
	755 :"aduersos legere et uenientum discere uultus.",
	756 :"'Nunc age, Dardaniam prolem quae deinde sequatur",
	757 :"gloria, qui maneant Itala de gente nepotes,",
	758 :"inlustris animas nostrumque in nomen ituras,",
	759 :"expediam dictis, et te tua fata docebo.",
	760 :"ille, uides, pura iuuenis qui nititur hasta,",
	761 :"proxima sorte tenet lucis loca, primus ad auras",
	762 :"aetherias Italo commixtus sanguine surget,",
	763 :"Siluius, Albanum nomen, tua postuma proles,",
	764 :"quem tibi longaeuo serum Lauinia coniunx",
	765 :"educet siluis regem regumque parentem,",
	766 :"unde genus Longa nostrum dominabitur Alba.",
	767 :"proximus ille Procas, Troianae gloria gentis,",
	768 :"et Capys et Numitor et qui te nomine reddet",
	769 :"Siluius Aeneas, pariter pietate uel armis",
	770 :"egregius, si umquam regnandam acceperit Albam.",
	771 :"qui iuuenes! quantas ostentant, aspice, uiris",
	772 :"atque umbrata gerunt ciuili tempora quercu!",
	773 :"hi tibi Nomentum et Gabios urbemque Fidenam,",
	774 :"hi Collatinas imponent montibus arces,",
	775 :"Pometios Castrumque Inui Bolamque Coramque;",
	776 :"haec tum nomina erunt, nunc sunt sine nomine terrae.",
	777 :"quin et auo comitem sese Mauortius addet",
	778 :"Romulus, Assaraci quem sanguinis Ilia mater",
	779 :"educet. uiden, ut geminae stant uertice cristae",
	780 :"et pater ipse suo superum iam signat honore?",
	781 :"en huius, nate, auspiciis illa incluta Roma",
	782 :"imperium terris, animos aequabit Olympo,",
	783 :"septemque una sibi muro circumdabit arces,",
	784 :"felix prole uirum: qualis Berecyntia mater",
	785 :"inuehitur curru Phrygias turrita per urbes",
	786 :"laeta deum partu, centum complexa nepotes,",
	787 :"omnis caelicolas, omnis supera alta tenentis.",
	788 :"huc geminas nunc flecte acies, hanc aspice gentem",
	789 :"Romanosque tuos. hic Caesar et omnis Iuli",
	790 :"progenies magnum caeli uentura sub axem.",
	791 :"hic uir, hic est, tibi quem promitti saepius audis,",
	792 :"Augustus Caesar, diui genus, aurea condet",
	793 :"saecula qui rursus Latio regnata per arua",
	794 :"Saturno quondam, super et Garamantas et Indos",
	795 :"proferet imperium; iacet extra sidera tellus,",
	796 :"extra anni solisque uias, ubi caelifer Atlas",
	797 :"axem umero torquet stellis ardentibus aptum.",
	798 :"huius in aduentum iam nunc et Caspia regna",
	799 :"responsis horrent diuum et Maeotia tellus,",
	800 :"et septemgemini turbant trepida ostia Nili.",
	801 :"nec uero Alcides tantum telluris obiuit,",
	802 :"fixerit aeripedem ceruam licet, aut Erymanthi",
	803 :"pacarit nemora et Lernam tremefecerit arcu;",
	804 :"nec qui pampineis uictor iuga flectit habenis",
	805 :"Liber, agens celso Nysae de uertice tigris.",
	806 :"et dubitamus adhuc uirtutem extendere factis,",
	807 :"aut metus Ausonia prohibet consistere terra?",
	808 :"quis procul ille autem ramis insignis oliuae",
	809 :"sacra ferens? nosco crinis incanaque menta",
	810 :"regis Romani primam qui legibus urbem",
	811 :"fundabit, Curibus paruis et paupere terra",
	812 :"missus in imperium magnum. cui deinde subibit",
	813 :"otia qui rumpet patriae residesque mouebit",
	814 :"Tullus in arma uiros et iam desueta triumphis",
	815 :"agmina. quem iuxta sequitur iactantior Ancus",
	816 :"nunc quoque iam nimium gaudens popularibus auris.",
	817 :"uis et Tarquinios reges animamque superbam",
	818 :"ultoris Bruti, fascisque uidere receptos?",
	819 :"consulis imperium hic primus saeuasque securis",
	820 :"accipiet, natosque pater noua bella mouentis",
	821 :"ad poenam pulchra pro libertate uocabit,",
	822 :"infelix, utcumque ferent ea facta minores:",
	823 :"uincet amor patriae laudumque immensa cupido.",
	824 :"quin Decios Drusosque procul saeuumque securi",
	825 :"aspice Torquatum et referentem signa Camillum.",
	826 :"illae autem paribus quas fulgere cernis in armis,",
	827 :"concordes animae nunc et dum nocte prementur,",
	828 :"heu quantum inter se bellum, si lumina uitae",
	829 :"attigerint, quantas acies stragemque ciebunt,",
	830 :"aggeribus socer Alpinis atque arce Monoeci",
	831 :"descendens, gener aduersis instructus Eois!",
	832 :"ne, pueri, ne tanta animis adsuescite bella",
	833 :"neu patriae ualidas in uiscera uertite uiris;",
	834 :"tuque prior, tu parce, genus qui ducis Olympo,",
	835 :"proice tela manu, sanguis meus!—",
	836 :"ille triumphata Capitolia ad alta Corintho",
	837 :"uictor aget currum caesis insignis Achiuis.",
	838 :"eruet ille Argos Agamemnoniasque Mycenas",
	839 :"ipsumque Aeaciden, genus armipotentis Achilli,",
	840 :"ultus auos Troiae templa et temerata Mineruae.",
	841 :"quis te, magne Cato, tacitum aut te, Cosse, relinquat?",
	842 :"quis Gracchi genus aut geminos, duo fulmina belli,",
	843 :"Scipiadas, cladem Libyae, paruoque potentem",
	844 :"Fabricium uel te sulco, Serrane, serentem?",
	845 :"quo fessum rapitis, Fabii? tu Maximus ille es,",
	846 :"unus qui nobis cunctando restituis rem.",
	847 :"excudent alii spirantia mollius aera",
	848 :"(credo equidem), uiuos ducent de marmore uultus,",
	849 :"orabunt causas melius, caelique meatus",
	850 :"describent radio et surgentia sidera dicent:",
	851 :"tu regere imperio populos, Romane, memento",
	852 :"(hae tibi erunt artes), pacique imponere morem,",
	853 :"parcere subiectis et debellare superbos.'",
	854 :"Sic pater Anchises, atque haec mirantibus addit:",
	855 :"'aspice, ut insignis spoliis Marcellus opimis",
	856 :"ingreditur uictorque uiros supereminet omnis.",
	857 :"hic rem Romanam magno turbante tumultu",
	858 :"sistet eques, sternet Poenos Gallumque rebellem,",
	859 :"tertiaque arma patri suspendet capta Quirino.'",
	860 :"atque hic Aeneas (una namque ire uidebat",
	861 :"egregium forma iuuenem et fulgentibus armis,",
	862 :"sed frons laeta parum et deiecto lumina uultu)",
	863 :"'quis, pater, ille, uirum qui sic comitatur euntem?",
	864 :"filius, anne aliquis magna de stirpe nepotum?",
	865 :"qui strepitus circa comitum! quantum instar in ipso!",
	866 :"sed nox atra caput tristi circumuolat umbra.'",
	867 :"tum pater Anchises lacrimis ingressus obortis:",
	868 :"'o gnate, ingentem luctum ne quaere tuorum;",
	869 :"ostendent terris hunc tantum fata nec ultra",
	870 :"esse sinent. nimium uobis Romana propago",
	871 :"uisa potens, superi, propria haec si dona fuissent.",
	872 :"quantos ille uirum magnam Mauortis ad urbem",
	873 :"campus aget gemitus! uel quae, Tiberine, uidebis",
	874 :"funera, cum tumulum praeterlabere recentem!",
	875 :"nec puer Iliaca quisquam de gente Latinos",
	876 :"in tantum spe tollet auos, nec Romula quondam",
	877 :"ullo se tantum tellus iactabit alumno.",
	878 :"heu pietas, heu prisca fides inuictaque bello",
	879 :"dextera! non illi se quisquam impune tulisset",
	880 :"obuius armato, seu cum pedes iret in hostem",
	881 :"seu spumantis equi foderet calcaribus armos.",
	882 :"heu, miserande puer, si qua fata aspera rumpas,",
	883 :"tu Marcellus eris. manibus date lilia plenis",
	884 :"purpureos spargam flores animamque nepotis",
	885 :"his saltem accumulem donis, et fungar inani",
	886 :"munere.' sic tota passim regione uagantur",
	887 :"aeris in campis latis atque omnia lustrant.",
	888 :"quae postquam Anchises natum per singula duxit",
	889 :"exim bella uiro memorat quae deinde gerenda,",
	890 :"Laurentisque docet populos urbemque Latini,",
	891 :"et quo quemque modo fugiatque feratque laborem.",
	892 :"incenditque animum famae uenientis amore,",
	893 :"Sunt geminae Somni portae, quarum altera fertur",
	894 :"cornea, qua ueris facilis datur exitus umbris,",
	895 :"altera candenti perfecta nitens elephanto,",
	896 :"sed falsa ad caelum mittunt insomnia Manes.",
	897 :"his ibi tum natum Anchises unaque Sibyllam",
	898 :"prosequitur dictis portaque emittit eburna,",
	899 :"ille uiam secat ad nauis sociosque reuisit.",
	900 :"Tum se ad Caietae recto fert limite portum.",
	901 :"ancora de prora iacitur; stant litore puppes."
};

console.log(arrayEneide);


$(document).ready(function(){
	$("#buttonEneide").click(function(){
		valoreIniziale = document.getElementById("idEneide0").value;
		valoreFinale = document.getElementById("idEneide1").value;

		rangeEneide=parseInt(valoreFinale, 10)-parseInt(valoreIniziale, 10)+1;

		numero=Math.ceil(Math.random()*rangeEneide);

		console.log("Range: "+rangeEneide);

		console.log(numero);

		//randno=arrayEneide[numero];

		randno="";

		for (let i = 0; i < 15; i++) {
			if (typeof(arrayEneide[numero+i])=="undefined") {
				arrayEneide[numero+i]="..."
			}
			randno+=arrayEneide[numero+i]+"\n";
		}

		$('#zonaDinamicaVerso').text("Verso iniziale numero: "+numero);

		$('#zonaDinamicaNow').text(randno);
	});
});